# Generated by Django 4.2.7 on 2025-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_businesspartnercategory_businesspartner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
