# Generated by Django 4.2.7 on 2025-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoiceline_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='businesspartnercategory',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='productservice',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='productservicecategory',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
    ]
