# Generated by Django 4.2.7 on 2026-02-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_nfe_notafiscal_notafiscalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='businesspartner',
            constraint=models.UniqueConstraint(fields=('company', 'identifier'), name='billing_bp_company_identifier_uniq'),
        ),
    ]
