# Generated by Django 4.2.7 on 2026-02-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_nfeinutilizacao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfeevento',
            new_name='billing_nfe_tipo_ev_6cf136_idx',
            old_name='billing_nfe_tipo_ev_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='nfeevento',
            new_name='billing_nfe_status__b1ea96_idx',
            old_name='billing_nfe_status__1d2e3f_idx',
        ),
        migrations.AlterField(
            model_name='nfeevento',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='nfeevento',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nfeinutilizacao',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='nfeinutilizacao',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
