# Generated by Django 4.2.7 on 2026-02-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_notafiscalreferencia'),
        ('billing', '0009_rename_billing_nfe_tipo_ev_0a1b2c_idx_billing_nfe_tipo_ev_6cf136_idx_and_more'),
    ]

    operations = [
    ]
