# Generated by Django 4.2.7 on 2026-02-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_merge_20260210_2150'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notafiscalreferencia',
            new_name='billing_not_chave_r_0dc62e_idx',
            old_name='billing_nfr_chave_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='notafiscalreferencia',
            new_name='billing_not_nota_re_24e025_idx',
            old_name='billing_nfr_nota_ref_idx',
        ),
        migrations.AlterField(
            model_name='notafiscalreferencia',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='notafiscalreferencia',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
