# Generated by Django 4.2.7 on 2026-02-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_notafiscalitem_valor_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código de 4 dígitos (ex.: 5101, 1202).', max_length=4, unique=True, verbose_name='Código CFOP')),
                ('descricao', models.CharField(help_text='Descrição oficial da operação conforme tabela CONFAZ.', max_length=300, verbose_name='Descrição')),
                ('tipo_operacao', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], db_index=True, help_text='E=Entrada (1xxx,2xxx,3xxx), S=Saída (5xxx,6xxx,7xxx).', max_length=1, verbose_name='Tipo operação')),
                ('grupo_analise', models.CharField(choices=[('venda', 'Venda'), ('devolucao', 'Devolução'), ('compra', 'Compra'), ('prestacao_servico', 'Prestação de serviço'), ('exportacao', 'Exportação'), ('outros', 'Outros')], db_index=True, default='outros', help_text='Agrupamento para relatórios: venda, devolução, compra, etc.', max_length=20, verbose_name='Grupo para análise')),
                ('ativo', models.BooleanField(default=True, help_text='Se false, código não é mais utilizado (histórico).', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'CFOP',
                'verbose_name_plural': 'CFOP',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='notafiscalitem',
            name='cfop_ref',
            field=models.ForeignKey(blank=True, help_text='Vínculo à tabela CFOP para análises por grupo (venda, devolução, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_itens', to='billing.cfop', verbose_name='CFOP (tabela)'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['cfop_ref'], name='billing_not_cfop_re_4cf7c5_idx'),
        ),
    ]
