# Generated by Django 4.2.7 on 2026-02-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_add_cfop_and_item_cfop_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='inventory_processed',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True after inventory movements have been created from this NF.', verbose_name='Processada no estoque'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='inventory_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data processamento estoque'),
        ),
    ]
