# Generated by Django 4.2.7

from django.db import migrations, models


def migrate_status(apps, schema_editor):
    NotaFiscal = apps.get_model("billing", "NotaFiscal")
    NotaFiscal.objects.filter(inventory_processed=True).update(
        inventory_processing_status="processed"
    )
    NotaFiscal.objects.filter(inventory_processed=False).update(
        inventory_processing_status="pending"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_add_inventory_processed_to_notafiscal"),
    ]

    operations = [
        migrations.AddField(
            model_name="notafiscal",
            name="inventory_processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processed", "Processed"),
                    ("all_skipped", "All Skipped"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="pending",
                help_text="pending=not run; processed=movements created; all_skipped=run but no movements; error=run with errors.",
                max_length=20,
                verbose_name="Status processamento estoque",
            ),
        ),
        migrations.RunPython(migrate_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="notafiscal",
            name="inventory_processed",
        ),
    ]
