# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0071_add_reconciliation_rule"),
        ("billing", "0015_replace_inventory_processed_with_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productservice",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Inventory (balance sheet) account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="COGS (income statement) account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="adjustment_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Inventory revaluation / adjustment account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales revenue account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="purchase_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Purchase / goods receipt account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="productservice",
            name="discount_given_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Discount given on sales account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
