# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_product_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnercategory',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='nfeevento',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='nfeinutilizacao',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalitem',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notafiscalreferencia',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productservice',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='productservicecategory',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_bus_company_b38146_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartnercategory',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_bus_company_61c459_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_con_company_6055da_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_inv_company_d4af83_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_inv_company_f569f6_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeevento',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_nfe_company_15fd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeinutilizacao',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_nfe_company_6457bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_not_company_9a308a_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_not_company_cb18a3_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalreferencia',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_not_company_f032be_idx'),
        ),
        migrations.AddIndex(
            model_name='productservice',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_pro_company_694e71_idx'),
        ),
        migrations.AddIndex(
            model_name='productservicecategory',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='billing_pro_company_ab299b_idx'),
        ),
    ]
