# Generated by Django 4.2.7 on 2026-05-01 17:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0041_customuser_prefer_dark_mode_explicit_and_more'),
        ('accounting', '0080_report_cache_updated_at_indexes'),
        ('billing', '0025_bpalias_name_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServiceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('kind', models.CharField(choices=[('code', 'Código ERP'), ('name', 'Nome')], db_index=True, default='code', max_length=8)),
                ('alias_identifier', models.CharField(db_index=True, help_text='String identificadora que deve resolver para este produto. Para ``kind=code``: código vendor/ERP (case-insensitive, espaços colapsados). Para ``kind=name``: token de nome normalizado (lower, sem acentos, ≤80 chars).', max_length=80)),
                ('review_status', models.CharField(choices=[('suggested', 'Sugerido'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], db_index=True, default='suggested', max_length=10)),
                ('source', models.CharField(default='nf_item', help_text='Como esta sugestão foi gerada.', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apelido de Produto',
                'verbose_name_plural': 'Apelidos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('name', models.CharField(help_text='Nome de exibição do grupo (geralmente o do primary_product).', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Produtos',
                'verbose_name_plural': 'Grupos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductServiceGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('role', models.CharField(choices=[('primary', 'Primário'), ('member', 'Membro')], default='member', max_length=10)),
                ('review_status', models.CharField(choices=[('suggested', 'Sugerido'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], db_index=True, default='suggested', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, help_text='Confiança máxima entre as evidências acumuladas (0..1).', max_digits=4)),
                ('hit_count', models.PositiveIntegerField(default=1, help_text="Quantos sinais distintos sustentam esta sugestão. Ao atingir o threshold (default 1 para auto_name por já ser match exato; 3 para auto_head por ser fuzzier) o membership promove automaticamente para 'accepted'.")),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Histórico de sinais que sustentam a sugestão: lista de {"method", "source_id", "at", "confidence", "kind"}.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membro de Grupo de Produtos',
                'verbose_name_plural': 'Membros de Grupos de Produtos',
            },
        ),
        migrations.RemoveIndex(
            model_name='businesspartner',
            name='billing_bus_company_b38146_idx',
        ),
        migrations.RemoveIndex(
            model_name='businesspartnercategory',
            name='billing_bus_company_61c459_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='billing_con_company_6055da_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_company_d4af83_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='billing_inv_company_f569f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfeevento',
            name='billing_nfe_company_15fd7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='nfeinutilizacao',
            name='billing_nfe_company_6457bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='notafiscal',
            name='billing_not_company_9a308a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notafiscalitem',
            name='billing_not_company_cb18a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='notafiscalreferencia',
            name='billing_not_company_f032be_idx',
        ),
        migrations.RemoveIndex(
            model_name='productservice',
            name='billing_pro_company_694e71_idx',
        ),
        migrations.RemoveIndex(
            model_name='productservicecategory',
            name='billing_pro_company_ab299b_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_company_80c0db_idx',
            old_name='billing_inv_company_fiscal_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_company_b457aa_idx',
            old_name='billing_inv_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicenflink',
            new_name='billing_inv_company_b6e847_idx',
            old_name='billing_invnflink_inv_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicenflink',
            new_name='billing_inv_company_41e4af_idx',
            old_name='billing_invnflink_nf_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicenflink',
            new_name='billing_inv_company_742d08_idx',
            old_name='billing_invnflink_rel_idx',
        ),
        migrations.RenameIndex(
            model_name='nftransactionlink',
            new_name='billing_nft_company_acfa1d_idx',
            old_name='billing_nflink_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='nftransactionlink',
            new_name='billing_nft_company_b3e4be_idx',
            old_name='billing_nflink_nf_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='nftransactionlink',
            new_name='billing_nft_company_716040_idx',
            old_name='billing_nflink_tx_rev_idx',
        ),
        migrations.RenameIndex(
            model_name='nftransactionlink',
            new_name='billing_nft_company_3df8bf_idx',
            old_name='billing_nflink_method_idx',
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='auto_accept_link_above',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.001'), help_text='Confiança a partir da qual o link é aceito automaticamente (sem revisão humana). Default 1.001 = nunca aceitar sozinho.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='link_amount_tolerance_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='Tolerância proporcional para casamento de valor (0.01 = 1%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='billingtenantconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartneralias',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='businesspartneralias',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartneralias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businesspartneralias',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartnergroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='businesspartnergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartnergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businesspartnergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartnergroupmembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='businesspartnergroupmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesspartnergroupmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businesspartnergroupmembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criticacknowledgement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='criticacknowledgement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criticacknowledgement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='criticacknowledgement',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='criticacknowledgement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicenflink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='invoicenflink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicenflink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicenflink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='nota_fiscal',
            field=models.ForeignKey(help_text='NF vinculada à transação.', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_links', to='billing.notafiscal'),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='transaction',
            field=models.ForeignKey(help_text='Lançamento contábil que corresponde à Nota Fiscal.', on_delete=django.db.models.deletion.CASCADE, related_name='nf_links', to='accounting.transaction'),
        ),
        migrations.AlterField(
            model_name='nftransactionlink',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businesspartner',
            index=models.Index(fields=['company', 'erp_id'], name='billing_bus_company_4e63f9_idx'),
        ),
        migrations.AddIndex(
            model_name='businesspartnercategory',
            index=models.Index(fields=['company', 'erp_id'], name='billing_bus_company_6ec212_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['company', 'erp_id'], name='billing_con_company_26d6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'erp_id'], name='billing_inv_company_c864b1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['company', 'erp_id'], name='billing_inv_company_ea3185_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeevento',
            index=models.Index(fields=['company', 'erp_id'], name='billing_nfe_company_8eb421_idx'),
        ),
        migrations.AddIndex(
            model_name='nfeinutilizacao',
            index=models.Index(fields=['company', 'erp_id'], name='billing_nfe_company_af9234_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['company', 'erp_id'], name='billing_not_company_877aca_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['company', 'erp_id'], name='billing_not_company_1bdf93_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalreferencia',
            index=models.Index(fields=['company', 'erp_id'], name='billing_not_company_28fa70_idx'),
        ),
        migrations.AddIndex(
            model_name='productservice',
            index=models.Index(fields=['company', 'erp_id'], name='billing_pro_company_03ba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='productservicecategory',
            index=models.Index(fields=['company', 'erp_id'], name='billing_pro_company_dfee10_idx'),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='billing.productservicegroup'),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='product_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='billing.productservice'),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_group_memberships_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicegroupmembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicegroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='productservicegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicegroup',
            name='primary_product',
            field=models.ForeignKey(help_text='Produto que representa o grupo nas listagens consolidadas.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_of_group', to='billing.productservice'),
        ),
        migrations.AddField(
            model_name='productservicegroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicealias',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='productservicealias',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicealias',
            name='product_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='billing.productservice'),
        ),
        migrations.AddField(
            model_name='productservicealias',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ps_aliases_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productservicealias',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productservicegroupmembership',
            index=models.Index(fields=['company', 'product_service', 'review_status'], name='psgm_company_prod_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productservicegroupmembership',
            index=models.Index(fields=['group', 'role'], name='psgm_group_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='productservicegroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'product_service'), name='psgm_unique_group_product'),
        ),
        migrations.AddConstraint(
            model_name='productservicegroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('review_status', 'accepted')), fields=('product_service',), name='psgm_one_accepted_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productservicegroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('group',), name='psgm_one_primary_per_group'),
        ),
        migrations.AddIndex(
            model_name='productservicegroup',
            index=models.Index(fields=['company', 'is_active'], name='psgroup_company_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='productservicegroup',
            constraint=models.UniqueConstraint(fields=('company', 'primary_product'), name='psgroup_one_primary_per_product'),
        ),
        migrations.AddIndex(
            model_name='productservicealias',
            index=models.Index(fields=['company', 'kind', 'alias_identifier', 'review_status'], name='psalias_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='productservicealias',
            constraint=models.UniqueConstraint(condition=models.Q(('review_status', 'accepted')), fields=('company', 'kind', 'alias_identifier'), name='psalias_one_accepted_per_identifier'),
        ),
        migrations.AddConstraint(
            model_name='productservicealias',
            constraint=models.UniqueConstraint(fields=('product_service', 'kind', 'alias_identifier'), name='psalias_unique_prod_identifier'),
        ),
    ]
