# Generated by Django 4.2.7 on 2026-04-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_rename_knowledge_b_knowled_123_idx_knowledge_b_knowled_a40a9a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answerfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
