# Generated by Django 4.2.7 on 2025-05-16 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('index_type', models.CharField(choices=[('inflation', 'Inflation Index'), ('currency', 'Currency Exchange Rate'), ('interest', 'Interest Rate'), ('custom', 'Custom Index')], max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('interpolation_strategy', models.CharField(choices=[('error', 'Error if missing'), ('last_known', 'Use last known value'), ('linear', 'Linear interpolation'), ('step', 'Step (carry last value)'), ('cumulative_rate', 'Cumulative Interest Rate')], default='error', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('quote_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='How frequently this index is typically quoted', max_length=20)),
                ('expected_quote_format', models.CharField(choices=[('daily_rate', 'Daily Rate'), ('monthly_rate', 'Monthly Rate'), ('accumulated', 'Accumulated'), ('absolute', 'Absolute')], default='monthly_rate', help_text='Defines how this index is quoted (e.g., rate or value)', max_length=50)),
                ('is_forecastable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.financialindex')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index', 'date'],
                'indexes': [models.Index(fields=['index', 'date'], name='core_indexq_index_i_884f1b_idx')],
                'unique_together': {('index', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialIndexQuoteForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estimated_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_quotes', to='core.financialindex')),
            ],
            options={
                'verbose_name': 'Financial Index Quote Forecast',
                'ordering': ['index', 'date'],
                'unique_together': {('index', 'date')},
            },
        ),
    ]
