# Generated by Django 4.2.7 on 2025-09-13 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('verb', models.CharField(max_length=64)),
                ('target_app', models.CharField(blank=True, default='', max_length=64)),
                ('target_model', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error')], db_index=True, default='info', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', '-created_at'], name='core_action_company_cc961b_idx'), models.Index(fields=['level', '-created_at'], name='core_action_level_b9fdbf_idx'), models.Index(fields=['verb', '-created_at'], name='core_action_verb_04b6a5_idx')],
            },
        ),
    ]
