# Generated by Django 4.2.7 on 2025-10-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0024_importsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_actionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('queue', models.CharField(blank=True, max_length=100, null=True)),
                ('worker', models.CharField(blank=True, max_length=200, null=True)),
                ('kind', models.CharField(db_index=True, default='other', max_length=64)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('SENT', 'SENT'), ('STARTED', 'STARTED'), ('PROGRESS', 'PROGRESS'), ('RETRY', 'RETRY'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED')], db_index=True, default='PENDING', max_length=16)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('done', models.PositiveIntegerField(blank=True, null=True)),
                ('by_category', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', '-created_at'], name='core_job_state_613f8b_idx'), models.Index(fields=['kind', '-created_at'], name='core_job_kind_f44288_idx')],
            },
        ),
    ]
