# Generated by Django 4.2.7 on 2025-10-20 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='job',
            name='tenant_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['tenant_id', '-created_at'], name='core_job_tenant__0308d3_idx'),
        ),
    ]
