# Generated by Django 4.2.7 on 2025-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_job_company_remove_job_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialindex',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='indexquote',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
    ]
