# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financialindex_notes_indexquote_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialindex',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='financialindexquoteforecast',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='indexquote',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='financialindex',
            index=models.Index(fields=['cliente_erp_id'], name='core_financ_cliente_7e9a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialindexquoteforecast',
            index=models.Index(fields=['cliente_erp_id'], name='core_financ_cliente_a47950_idx'),
        ),
        migrations.AddIndex(
            model_name='indexquote',
            index=models.Index(fields=['cliente_erp_id'], name='core_indexq_cliente_bfd3c4_idx'),
        ),
    ]
