# Generated by Django 4.2.7 on 2026-04-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_cliente_erp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialindex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indexquote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
