# Generated by Django 4.2.7 on 2025-11-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=16)),
                ('object_id', models.IntegerField()),
                ('rank', models.IntegerField(default=0)),
                ('suggested_value', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=32)),
                ('version_name', models.CharField(max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetrieverRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_type', models.CharField(max_length=32)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJudgment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=True)),
                ('edited_value', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='feedback.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('doctype', 'Document Type'), ('span', 'Span'), ('ecode', 'Event Code'), ('search', 'Search Results')], max_length=16)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.judgmentsession')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='feedback.candidateset'),
        ),
    ]
