# Generated by Django 4.2.7 on 2026-01-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpprovider',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='erpapidefinition',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='erpconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='erpprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
