# Generated by Django 4.2.7 on 2026-01-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0002_alter_erpprovider_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpapidefinition',
            name='default_param',
        ),
        migrations.AddField(
            model_name='erpapidefinition',
            name='method',
            field=models.CharField(default='POST', help_text='HTTP method (e.g. POST, GET).', max_length=10),
        ),
        migrations.AddField(
            model_name='erpapidefinition',
            name='url',
            field=models.URLField(default=0, help_text='Full URL for this API endpoint.', max_length=512),
            preserve_default=False,
        ),
    ]
