# Generated by Django 4.2.7 on 2026-01-30 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        ('erp_integrations', '0003_remove_erpapidefinition_default_param_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpApiEtlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('name', models.CharField(help_text='e.g. Omie Produtos', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('response_list_key', models.CharField(help_text='JSON key containing the array of records (e.g. produto_servico_cadastro)', max_length=120)),
                ('target_model', models.CharField(help_text='Target model: ProductService, ProductServiceCategory, etc.', max_length=100)),
                ('field_mappings', models.JSONField(default=dict, help_text='\n        Map API keys to model fields. Format: {"api_key": "model_field"}\n        Use __row_id for the row token (e.g. codigo -> __row_id for products).\n        Nested keys use dot notation: "dadosIbpt.aliqFederal" -> "some_field"\n        ')),
                ('default_values', models.JSONField(blank=True, default=dict, help_text='Default values, e.g. {"item_type": "product", "track_inventory": false}')),
                ('row_id_api_key', models.CharField(blank=True, help_text='API key whose value is used as __row_id (e.g. codigo). Same key can still map to a model field.', max_length=80)),
                ('category_from_same_response', models.BooleanField(default=False, help_text='If True, unique category keys are emitted as ProductServiceCategory rows first.')),
                ('category_name_key', models.CharField(blank=True, help_text='API key for category name (e.g. descricao_familia)', max_length=80)),
                ('category_id_key', models.CharField(blank=True, help_text='API key for stable category id (e.g. codigo_familia). Used for __row_id.', max_length=80)),
                ('category_target_model', models.CharField(blank=True, default='ProductServiceCategory', help_text='Model for category rows.', max_length=100)),
                ('category_fk_field', models.CharField(blank=True, default='category_fk', help_text='Target model FK field pointing to category (e.g. category_fk).', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ERP API ETL Mapping',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'response_list_key'], name='erp_integra_company_eedfe6_idx'), models.Index(fields=['company', 'is_active'], name='erp_integra_company_7dfc5c_idx')],
            },
        ),
    ]
