# Generated by Django 4.2.7 on 2026-03-06 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_integrations', '0004_add_erp_api_etl_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_rrule', models.CharField(blank=True, help_text='iCal RRULE for periodic runs (e.g. FREQ=HOURLY;INTERVAL=6)', max_length=500, null=True)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Override params for this job (e.g. pagina, registros_por_pagina)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial'), ('running', 'Running')], default='never', max_length=20)),
                ('last_sync_record_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ERP Sync Job',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='erpapidefinition',
            name='transform_config',
            field=models.JSONField(blank=True, default=None, help_text='Transform config spec: records extraction, explode rules, derived dates. See docs.', null=True),
        ),
        migrations.CreateModel(
            name='ERPSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('pages_fetched', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('records_extracted', models.IntegerField(default=0)),
                ('records_stored', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('diagnostics', models.JSONField(default=dict, help_text='Picked path, timing, retries, etc.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('request_payload_redacted', models.JSONField(blank=True, help_text='Request payload with app_key/app_secret masked', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='erp_integrations.erpsyncjob')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='erpsyncjob',
            name='api_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='erp_integrations.erpapidefinition'),
        ),
        migrations.AddField(
            model_name='erpsyncjob',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='erpsyncjob',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='erp_integrations.erpconnection'),
        ),
        migrations.AddField(
            model_name='erpsyncjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncjob',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ERPRawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_call', models.CharField(db_index=True, max_length=128)),
                ('page_number', models.IntegerField()),
                ('record_index', models.IntegerField()),
                ('global_index', models.IntegerField()),
                ('page_records_count', models.IntegerField()),
                ('total_pages', models.IntegerField()),
                ('total_records', models.IntegerField()),
                ('page_response_header', models.JSONField(default=dict, help_text='All top-level keys from the page response except the records array')),
                ('data', models.JSONField()),
                ('record_hash', models.CharField(db_index=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_raw_records', to='multitenancy.company')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='erp_integrations.erpsyncrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='erpsyncrun',
            index=models.Index(fields=['job', '-started_at'], name='erp_integra_job_id_b48a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='erpsyncrun',
            index=models.Index(fields=['status'], name='erp_integra_status_8f155a_idx'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['company', 'api_call', '-fetched_at'], name='erp_integra_company_eedd71_idx'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['sync_run', 'page_number', 'record_index'], name='erp_integra_sync_ru_3a170a_idx'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['sync_run', 'global_index'], name='erp_integra_sync_ru_9c7ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['record_hash'], name='erp_integra_record__b70fcb_idx'),
        ),
    ]
