# Generated by Django 4.2.7 on 2026-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0005_erpsyncjob_erpapidefinition_transform_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpsyncjob',
            name='fetch_config',
            field=models.JSONField(blank=True, default=dict, help_text='Static/variable fetch rules: mode, static_params, date_dimension, bounds, cursor. See erp_integrations.services.fetch_config.'),
        ),
    ]
