# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0006_erpsyncjob_fetch_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpapietlmapping',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='erpapietlmapping',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='erp_integra_company_8d637e_idx'),
        ),
    ]
