# Generated by Django 4.2.7 on 2026-03-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0007_add_cliente_erp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpapidefinition',
            name='unique_id_config',
            field=models.JSONField(blank=True, default=None, help_text='How to derive a stable id per item for dedup within this api_call: mode single_path with path, or mode composite with paths + optional separator; on_duplicate: update | flag | add.', null=True),
        ),
        migrations.AddField(
            model_name='erprawrecord',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable id extracted from item (single path or composite); scoped with api_call for lookups.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='erprawrecord',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='True when created with on_duplicate=flag and same external_id already existed.'),
        ),
        migrations.AddField(
            model_name='erpsyncrun',
            name='records_skipped',
            field=models.IntegerField(default=0, help_text='Items skipped on sync (unchanged hash when on_duplicate=update).'),
        ),
        migrations.AddField(
            model_name='erpsyncrun',
            name='records_updated',
            field=models.IntegerField(default=0, help_text='Existing raw rows updated when on_duplicate=update.'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['company', 'api_call', 'external_id'], name='erp_integra_company_06b750_idx'),
        ),
    ]
