# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_integrations', '0009_position_employee_per_company_unique_and_base_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpsyncrun',
            name='segments_total',
            field=models.IntegerField(default=0, help_text='Total segments planned for this run.'),
        ),
        migrations.AddField(
            model_name='erpsyncrun',
            name='segments_completed',
            field=models.IntegerField(default=0, help_text='Segments successfully completed before stopping.'),
        ),
        migrations.AddField(
            model_name='erpsyncrun',
            name='failed_segment_label',
            field=models.CharField(blank=True, help_text="Label of the segment that failed (e.g. '2026-03-16..2026-03-16').", max_length=64, null=True),
        ),
    ]
