# Generated by Django 4.2.7 on 2026-04-20 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0032_rename_cliente_erp_id_to_erp_id'),
        ('erp_integrations', '0011_rename_cliente_erp_id_to_erp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPSyncPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_rrule', models.CharField(blank=True, help_text='iCal RRULE for periodic runs (e.g. FREQ=HOURLY;INTERVAL=6).', max_length=500, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(choices=[('never', 'Never'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial'), ('running', 'Running')], default='never', max_length=20)),
                ('last_run_record_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ERP Sync Pipeline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('records_extracted', models.IntegerField(default=0)),
                ('records_stored', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('diagnostics', models.JSONField(default=dict, help_text='Per-step diagnostics, bindings resolved, fanout counts, retries, etc.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('failed_step_order', models.PositiveIntegerField(blank=True, help_text='Order (1-based) of the step that failed, if any.', null=True)),
                ('is_sandbox', models.BooleanField(default=False, help_text='True for ad-hoc sandbox runs (preview-only, not persisted raw records).')),
            ],
            options={
                'verbose_name': 'ERP Sync Pipeline Run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ERPSyncPipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('order', models.PositiveIntegerField(help_text='1-based execution order within the pipeline.')),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Static param overrides for this step (merged before bindings).')),
                ('param_bindings', models.JSONField(blank=True, default=list, help_text='Ordered list of bindings that derive params from prior step outputs. See docstring.')),
                ('select_fields', models.JSONField(blank=True, default=None, help_text='Optional JMESPath expression for preview projection (sandbox/dry_run). Does not affect stored ERPRawRecord.data.', null=True)),
            ],
            options={
                'verbose_name': 'ERP Sync Pipeline Step',
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.AddField(
            model_name='erprawrecord',
            name='pipeline_step_order',
            field=models.IntegerField(blank=True, help_text='Order (1-based) of the pipeline step that produced this record.', null=True),
        ),
        migrations.AlterField(
            model_name='erprawrecord',
            name='sync_run',
            field=models.ForeignKey(blank=True, help_text='Set when record came from a single-job sync. Null when from a pipeline run.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='erp_integrations.erpsyncrun'),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinestep',
            name='api_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_steps', to='erp_integrations.erpapidefinition'),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinestep',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinestep',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='erp_integrations.erpsyncpipeline'),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinestep',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinerun',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinerun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinerun',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Null for ad-hoc sandbox executions with no persisted pipeline.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='erp_integrations.erpsyncpipeline'),
        ),
        migrations.AddField(
            model_name='erpsyncpipelinerun',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncpipeline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='erpsyncpipeline',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_pipelines', to='erp_integrations.erpconnection'),
        ),
        migrations.AddField(
            model_name='erpsyncpipeline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erpsyncpipeline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='erprawrecord',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, help_text='Set when record came from a pipeline execution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='erp_integrations.erpsyncpipelinerun'),
        ),
        migrations.AddIndex(
            model_name='erprawrecord',
            index=models.Index(fields=['pipeline_run', 'pipeline_step_order'], name='erp_integra_pipelin_d14cbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='erpsyncpipelinestep',
            unique_together={('pipeline', 'order')},
        ),
        migrations.AddIndex(
            model_name='erpsyncpipelinerun',
            index=models.Index(fields=['pipeline', '-started_at'], name='erp_integra_pipelin_ab2192_idx'),
        ),
        migrations.AddIndex(
            model_name='erpsyncpipelinerun',
            index=models.Index(fields=['status'], name='erp_integra_status_4234bc_idx'),
        ),
    ]
