# Generated by Django 4.2.7 on 2024-12-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0005_alter_company_subdomain'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='multitenancy.company'),
            preserve_default=False,
        ),
    ]
