# Generated by Django 4.2.7 on 2024-12-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0005_alter_company_subdomain'),
        ('hr', '0003_employee_is_active_position_alter_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='bank_hours_2021_2022',
            new_name='bank_hours',
        ),
        migrations.AddField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'pay_date')},
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('employee', 'date')},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bank_hours_2022_2023',
        ),
    ]
