# Generated by Django 4.2.7 on 2024-12-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_rename_bank_hours_2021_2022_payroll_bank_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='course_discount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='health_insurance_deduction',
        ),
        migrations.AddField(
            model_name='payroll',
            name='adjustment_details',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RecurringAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('additional', 'Additional'), ('deduction', 'Deduction')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('base_for_inss', models.BooleanField(default=False)),
                ('base_for_fgts', models.BooleanField(default=False)),
                ('base_for_irpf', models.BooleanField(default=False)),
                ('value_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage of Base Salary')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_adjustments', to='hr.employee')),
            ],
        ),
    ]
