# Generated by Django 4.2.7 on 2024-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_payroll_course_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankhours',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='timetracking',
            options={'verbose_name': 'Employee Attendance', 'verbose_name_plural': 'Employee Attendances'},
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recurringadjustment',
            name='value',
        ),
        migrations.RemoveField(
            model_name='recurringadjustment',
            name='value_type',
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='calculation_formula',
            field=models.TextField(blank=True, help_text="Custom formula for dynamic adjustment calculations. Example: '(days_present * 8) + total_overtime_hours'", null=True),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='employer_cost_formula',
            field=models.TextField(blank=True, help_text="Custom formula for employer cost calculations. Example: 'adjustment_value * 0.2'", null=True),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='absence_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='bank_hours_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated bank hours balance for this month.', max_digits=10),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='days_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='days_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='effective_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='month',
            field=models.DateField(default='2024-12-01', help_text='Represents the first day of the month for this record.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetracking',
            name='overtime_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='overtime_hours_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours paid this month.', max_digits=7),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='total_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='vacation_days_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='vacation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='vacation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='vacation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee'),
        ),
        #migrations.AlterUniqueTogether(
        #    name='timetracking',
        #    unique_together={('employee', 'month')},
        #),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='BankHours',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='overtime_hours',
        ),
    ]
