# Generated by Django 4.2.7 on 2024-12-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_bankhours_employee_remove_vacation_employee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('employee', 'month')},
        ),
    ]
