# Generated by Django 4.2.7 on 2024-12-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_timetracking_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='overtime_eligible',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='vacation_status',
        ),
    ]
