# Generated by Django 4.2.7 on 2024-12-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_remove_timetracking_overtime_eligible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetracking',
            old_name='month',
            new_name='month_date',
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('employee', 'month_date')},
        ),
    ]
