# Generated by Django 4.2.7 on 2024-12-28 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0012_alter_company_created_at_alter_company_updated_at_and_more'),
        ('hr', '0009_rename_month_timetracking_month_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='bonus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='bonus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpi',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='kpi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='position',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
    ]
