# Generated by Django 4.2.7 on 2025-01-02 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_account_created_at_alter_account_updated_at_and_more'),
        ('hr', '0010_bonus_company_bonus_created_at_bonus_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringadjustment',
            name='default_account',
            field=models.ManyToManyField(blank=True, default=None, to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='recurringadjustment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='recurringadjustment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
    ]
