# Generated by Django 4.2.7 on 2025-01-16 15:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0015_remove_integrationrule_target_module_and_more'),
        ('hr', '0012_alter_bonus_created_at_alter_bonus_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='calculation_formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='adjustment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='fgts',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='inss_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='irrf_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='recurringadjustment',
            name='calculation_formula',
            field=models.TextField(blank=True, help_text="E.g. '(days_present * 8) + total_overtime_hours'", null=True),
        ),
        migrations.AlterField(
            model_name='recurringadjustment',
            name='employer_cost_formula',
            field=models.TextField(blank=True, help_text="E.g. 'adjustment_value * 0.2'", null=True),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='month_date',
            field=models.DateField(help_text='First day of that month.'),
        ),
    ]
