# Generated by Django 4.2.7 on 2025-02-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0018_alter_integrationrule_company_and_more'),
        ('hr', '0013_timetracking_status_alter_bonus_calculation_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpi',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurringadjustment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
    ]
