# Generated by Django 4.2.7 on 2025-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_bonus_company_alter_employee_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='month_date',
            field=models.DateField(default="2025-01-01", help_text='First day of that month.'),
            preserve_default=False,
        ),
    ]
