# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_bonus_notes_employee_notes_kpi_notes_payroll_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recurringadjustment',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_bonus_company_eaddb4_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_employee_company_742817_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_kpi_company_b60026_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_position_company_da5a89_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringadjustment',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_recurrin_company_4ab3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='hr_timetrac_company_8c7908_idx'),
        ),
    ]
