"""
Django settings for nord_backend project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta 

import logging

DEBUG = True
IMPORT_DEBUG = True
AUTH_OFF = True

# NFe import: allow up to 100 XML files per request (must be >= billing.views_nfe.MAX_FILES)
DATA_UPLOAD_MAX_NUMBER_FILES = 10000

class SlowOnlyFilter(logging.Filter):
    def __init__(self, threshold_ms=200):
        super().__init__()
        self.threshold = float(threshold_ms) / 1000.0  # seconds

    def filter(self, record):
        # django.db.backends logs include `duration` in seconds
        dur = getattr(record, "duration", None)
        return dur is not None and dur >= self.threshold

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "ctx": {
            "format": "%(levelname)s %(asctime)s importer %(message)s | run_id=%(run_id)s company=%(company_id)s model=%(model)s row_id=%(row_id)s"
        },
        "plain": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s"
        },
        # IMPORTANT: let Gunicorn build the access line; we just print it.
        "gunicorn_access": {
            "format": "%(message)s"
        },
    },
    "handlers": {
        "console_plain": {
            "class": "logging.StreamHandler",
            "formatter": "plain",
            "level": "INFO",
        },
        "console_ctx": {
            "class": "logging.StreamHandler",
            "formatter": "ctx",
            "level": "DEBUG",
        },
        "gunicorn_access": {
            "class": "logging.StreamHandler",
            "formatter": "gunicorn_access",
            "level": "INFO",
        },
    },
    "loggers": {
        "importer": {
            "handlers": ["console_ctx"],
            "level": "DEBUG",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console_plain"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["gunicorn_access"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console_plain"],
            "level": "INFO",
        },
        "recon": {
            "handlers": ["console_plain"],
            "level": "DEBUG",   # or INFO in prod
            "propagate": False,
        },
    },
}

LOGGING["handlers"]["console_plain"]["level"] = "DEBUG"

LOGGING["loggers"]["recon"] = {
    "handlers": ["console_plain"],
    "level": "DEBUG",           # was INFO
    "propagate": False,
}

LOGGING["loggers"]["chat"] = {
    "handlers": ["console_plain"],
    "level": "DEBUG",
    "propagate": False,
}
LOGGING["loggers"]["chat.view"] = {
    "handlers": ["console_plain"],
    "level": "DEBUG",
    "propagate": False,
}
LOGGING["loggers"]["chat.llm"] = {
    "handlers": ["console_plain"],
    "level": "DEBUG",
    "propagate": False,
}
# NFe eventos/inutilização: import e detecção de tipo (DEBUG = ver parse e doc_type por arquivo)
# Handler em stdout para garantir visibilidade no Railway / Docker (capturam stdout)
LOGGING["handlers"]["console_stdout"] = {
    "class": "logging.StreamHandler",
    "formatter": "plain",
    "level": "DEBUG",
    "stream": "ext://sys.stdout",
}
LOGGING["loggers"]["billing.nfe_events"] = {
    "handlers": ["console_stdout", "console_plain"],
    "level": "DEBUG",
    "propagate": False,
}
# Optional: see requests→urllib3 connection lines (INFO is usually enough)
import logging as _pylog
_pylog.getLogger("urllib3.connectionpool").setLevel(_pylog.INFO)

APPEND_SLASH = True  # keep this; helps GET/HEAD without slash

# Feature flag for Retool authentication
ALLOW_RETOOL_AUTHENTICATION = True
RETOOL_AUTH_ORIGIN = "https://nordventures.retool.com"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rc^*w^w&6g9_(uvx#6s*bnt!w)l0rdi%!l7mv#y%uc&x%wo5pk'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ["*"]

# FORM SUBMISSION
# Comment out the following line and place your railway URL, and your production URL in the array.
# CSRF_TRUSTED_ORIGINS = ["*"]

AUTH_USER_MODEL = 'multitenancy.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'multitenancy',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'core.apps.CoreConfig',#'core',
    'accounting',
    'accounting.reports.apps.ReportsConfig',
    'hr',
    'billing',
    'inventory',
    'ML',
    'django_celery_results',
    'pgvector.django',
    'npl',              # nova app do pipeline
    'feedback',         # app de feedback supervisionado
    'knowledge_base',   # NotebookLM-like document Q&A with Gemini File Search
    'erp_integrations', # ERP integration pipeline (Omie, etc.)
    'api_meta',         # Introspection / Meta-API for OpenClaw agent
    'mcp_server',       # Stdio MCP server exposing read-only tools (run via mgmt cmd)
    'agent',            # Internal Sysnord agent (OAuth → OpenAI, chat history)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'multitenancy.middleware.TenantMiddleware',
    'crum.CurrentRequestUserMiddleware',
    'api_meta.middleware.OpenClawReadOnlyMiddleware',
]

ROOT_URLCONF = 'nord_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nord_backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
        #'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    "EXCEPTION_HANDLER": "core.utils.error_reporting.custom_exception_handler",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Global pagination: opt-in. Callers that don't send ?page / ?page_size
    # / ?paginate=true get the legacy flat-array shape; new callers opt into
    # the paginated envelope by passing any of those params. This matches
    # the pre-pagination behavior the frontend's unwrapList helper expects.
    "DEFAULT_PAGINATION_CLASS": "core.utils.pagination.OptInPageNumberPagination",
    "PAGE_SIZE": 1000,
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#postgresql://postgres:OpiRdctRUwIVWoFbhOnfBQLmIPDarkXG@caboose.proxy.rlwy.net:11644/railway

#postgresql://postgres:RredJeomPHdFbnFgXgIWSWxAQLkvbTRg@switchyard.proxy.rlwy.net:45690/railway
#postgres://postgres:a9X9kk28TgaZC_HCHo9iMawHs.ywEbvK@switchback.proxy.rlwy.net:17976/railway
#postgresql://postgres:kxHcvhsqrtHzyStXGoNxyBKwRTJmuJkY@yamanote.proxy.rlwy.net:13795/railway
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "railway",
        "USER": "postgres",
        "PASSWORD": "a9X9kk28TgaZC_HCHo9iMawHs.ywEbvK",
        "HOST": "switchback.proxy.rlwy.net",
        "PORT": "17976",          # ← must match the public URL port
        #"OPTIONS": {"sslmode": "require"},
    },
    "old": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "railway",
        "USER": "postgres",
        "PASSWORD": "kxHcvhsqrtHzyStXGoNxyBKwRTJmuJkY",
        "HOST": "yamanote.proxy.rlwy.net",
        "PORT": "13795",          # ← must match the public URL port
        #"OPTIONS": {"sslmode": "require"},
    }
}


#if os.getenv("RAILWAY_ENVIRONMENT"):
if os.environ.get('PGDATABASE'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': os.environ["PGDATABASE"],
            'USER': os.environ["PGUSER"],
            'PASSWORD': os.environ["PGPASSWORD"],
            'HOST': os.environ["PGHOST"],
            'PORT': os.environ["PGPORT"],
        }
    }

# Apply local_credentials.ini overrides (adds 'production' alias for cloning,
# switches 'default' to homologation when mode=local/homolog, unless PGDATABASE
# env vars already override default).
try:
    from nord_backend.local_settings_loader import (
        get_database_config as _get_db_cfg,
        get_environment_mode as _get_env_mode,
    )
    _mode = _get_env_mode()
    ENVIRONMENT_MODE = _mode
    if _mode in ("local", "homolog", "homologation"):
        _prod_cfg = _get_db_cfg("production")
        if _prod_cfg:
            DATABASES["production"] = _prod_cfg
        # Only override default if no explicit env-var DB is set
        if not os.environ.get("PGDATABASE"):
            _default_cfg = _get_db_cfg("default")
            if _default_cfg:
                DATABASES["default"] = _default_cfg
except Exception:
    pass

# Email config — env-driven so the SMTP relay can be swapped without
# a code deploy. Defaults preserve the historical Office 365 setup
# (smtp.office365.com:587 + TLS) so any environment that doesn't set
# these explicitly keeps working.
#
# Common provider configs:
#
#   * Office 365 (default):
#       EMAIL_HOST            = smtp.office365.com
#       EMAIL_PORT            = 587
#       EMAIL_USE_TLS         = true
#       EMAIL_HOST_USER       = <real mailbox address>
#       EMAIL_HOST_PASSWORD   = <password or app password>
#       DEFAULT_FROM_EMAIL    = <usually = EMAIL_HOST_USER>
#
#     Note: M365 disables SmtpClientAuthentication tenant-wide by
#     default since 2020. Either enable per-mailbox SMTP AUTH in the
#     M365 admin centre or use a transactional provider instead.
#
#   * Resend (recommended for transactional):
#       EMAIL_HOST            = smtp.resend.com
#       EMAIL_PORT            = 587
#       EMAIL_USE_TLS         = true
#       EMAIL_HOST_USER       = resend
#       EMAIL_HOST_PASSWORD   = <Resend API key, "re_..." prefix>
#       DEFAULT_FROM_EMAIL    = noreply@yourverifieddomain.com
#
#     With Resend, ``EMAIL_HOST_USER`` is the literal string "resend"
#     -- not an email address. ``DEFAULT_FROM_EMAIL`` MUST be set
#     explicitly to a verified-domain address; the previous fallback
#     ``DEFAULT_FROM_EMAIL = EMAIL_HOST_USER`` would have produced
#     "From: resend" which Resend rejects.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.office365.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").strip().lower() in (
    "true", "1", "yes",
)
# SSL is mutually exclusive with TLS in Django's SMTP backend; set only
# one. Most modern providers use TLS on 587 (STARTTLS). Enable SSL for
# port-465 setups.
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").strip().lower() in (
    "true", "1", "yes",
)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# Independent env var so providers like Resend/SendGrid (where
# EMAIL_HOST_USER is a vendor token, not an address) work without a
# code change. Falls back to EMAIL_HOST_USER for the Office 365 / Gmail
# style setup where the SMTP user IS the sender address.
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
PASSWORD_RESET_EMAIL_COOLDOWN = int(os.getenv("PASSWORD_RESET_EMAIL_COOLDOWN", 5))  # minutes
TEMP_PASSWORD = os.getenv("TEMP_PASSWORD", 'NordTemp123')
# Celery / Redis
#CELERY_BROKER_URL = os.environ["REDIS_URL"] #
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# Optional task time limits (protects against runaway jobs).
#
# Default raised to 30 minutes after the Phase 6.z-f perf fix: most
# v2 imports now finish in <60s thanks to LookupCache, but a huge
# template (10k+ rows with many FKs) can still push past 10. The
# cap guards against genuine runaways.
#
# Historical bug: the original comments claimed 12/15 min, but the
# math was (T-3)*60 = 7 min soft + T*60 = 10 min hard. Rewritten to
# be explicit and correct.
CELERY_TASK_T_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", 30))  # minutes
CELERY_TASK_SOFT_TIME_LIMIT = max(60, (CELERY_TASK_T_LIMIT - 5) * 60)  # 25 min default
CELERY_TASK_TIME_LIMIT = CELERY_TASK_T_LIMIT * 60                      # 30 min default

# Celery Beat: periodic tasks
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    "embedding-backfill-every-30min": {
        "task": "accounting.tasks.generate_missing_embeddings",
        "schedule": crontab(minute="*/30"),
        "options": {"queue": "celery"},
        "kwargs": {"per_model_limit": 200},
    },
    "erp-sync-scheduled-jobs": {
        "task": "erp_integrations.tasks.run_all_due_syncs",
        "schedule": crontab(minute="*/15"),
        "options": {"queue": "celery"},
    },
    # Phase 6.z-f — reap v2 sessions stuck in analyzing / committing past
    # the Celery hard time limit. The worker could have been SIGKILL'd,
    # container restarted, or broker hung — any of which leaves the row
    # in a non-terminal status the frontend polls forever. Runs every
    # 5 minutes; sessions older than CELERY_TASK_TIME_LIMIT flip to
    # ``error`` with a "timeout" stage in result.
    "imports-v2-reap-stale-sessions": {
        "task": "imports_v2.reap_stale_sessions",
        "schedule": crontab(minute="*/5"),
        "options": {"queue": "celery"},
    },
    # Weekly activity digest for the platform admin. Mondays 11:00 UTC
    # ≈ 08:00 São Paulo (UTC-3), so the admin has it waiting at the
    # start of the week. Recipient is ADMIN_DIGEST_EMAIL env var or
    # the dcaffaro user's email as a fallback. See
    # core/tasks_activity_digest.py for the logic.
    "activity-digest-weekly": {
        "task": "core.tasks_activity_digest.send_weekly_digest",
        "schedule": crontab(day_of_week=1, hour=11, minute=0),
        "options": {"queue": "celery"},
        "kwargs": {"days": 7},
    },
    # Agent playbooks — Phase 1 wave 3. The task scans active
    # AgentPlaybook rows whose ``schedule_cron`` has fired since
    # ``last_run_at`` and dispatches them via run_agent_playbook
    # (which honours the AGENT_ALLOW_WRITES kill-switch downstream).
    # 1-minute beat resolution is sufficient — the cron expressions
    # users write rarely need sub-minute precision.
    "agent-playbooks-poll": {
        "task": "agent.tasks.run_due_playbooks",
        "schedule": crontab(minute="*"),
        "options": {"queue": "celery"},
    },
}

if not os.getenv("REDIS_URL"):
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

IMPORT_MAX_BATCH_SIZE = 1000
INTEGRATION_MAX_BATCH_SIZE = 500

OPEN_AI_API_KEY = os.getenv("OPEN_AI_API_KEY")

# ---- Embeddings config (single-source) ----
EMBED_INTERNAL_HOST = os.getenv("EMBED_INTERNAL_HOST")  # e.g. "embedding-service.railway.internal"
EMBED_PORT          = int(os.getenv("EMBED_PORT", "11434"))
EMBED_BASE_URL      = os.getenv("EMBED_BASE_URL", "https://embedding-service.up.railway.app")   # optional fallback for local/testing
EMBED_PATH          = os.getenv("EMBED_PATH", "/api/embeddings")

EMBED_MODEL         = os.getenv("EMBED_MODEL", "nomic-embed-text")
EMBED_DIM           = int(os.getenv("EMBED_DIM", "768"))
EMBED_TIMEOUT_S     = float(os.getenv("EMBED_TIMEOUT_S", "300"))
EMBED_NUM_THREAD    = int(os.getenv("EMBED_NUM_THREAD", "20"))
EMBED_KEEP_ALIVE    = os.getenv("EMBED_KEEP_ALIVE", "45m")
EMBED_BATCH_SIZE    = max(1, int(os.getenv("EMBED_BATCH_SIZE", "128")))
EMBED_LIMIT_PER_MODEL = max(1, int(os.getenv("EMBED_LIMIT_PER_MODEL", "2000")))
EMBED_API_KEY       = os.getenv("EMBED_API_KEY")  # optional; not needed for internal by default
EMBED_PARALLEL_REQUESTS = int(os.getenv("OLLAMA_NUM_PARALLEL", "5"))
EMBED_TOKEN_LIMIT = int(os.getenv("EMBED_TOKEN_LIMIT", "2048"))


# --- External dependencies the Chat service calls ---
EMBED_SVC_URL = EMBED_BASE_URL  # Service A
EMBED_TIMEOUT = float(os.getenv("EMBED_TIMEOUT", "15"))      # per request
EMBED_KEEP    = EMBED_KEEP_ALIVE

LLM_BASE_URL  = os.getenv("LLM_BASE_URL", "https://chat-service-production-d54a.up.railway.app")  # local Ollama on Service B
LLM_TIMEOUT   = float(os.getenv("LLM_TIMEOUT", "30"))

LLM_BASE_URL      = os.getenv("LLM_BASE_URL", "http://chat-service.railway.internal:11434")
LLM_BASE_URL  = "https://chat-service-production-d54a.up.railway.app"
LLM_GENERATE_PATH = os.getenv("LLM_GENERATE_PATH", "/api/generate")
LLM_MODEL         = os.getenv("LLM_MODEL", "llama3.2:1b-instruct-q4_K_M")
LLM_NUM_THREAD = int(os.getenv("LLM_NUM_THREAD", "6"))
LLM_TIMEOUT_S     = float(os.getenv("LLM_TIMEOUT_S", "25"))

LLM_ENABLE_PROBE  = os.getenv("LLM_ENABLE_PROBE", "0") in ("1","true","yes")
LLM_ENABLE_WARMUP = os.getenv("LLM_ENABLE_WARMUP", "0") in ("1","true","yes")

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Uploaded files (chat attachments, etc.). On Railway, set MEDIA_ROOT
# to the mount path of an attached Volume (e.g. "/data") so files
# survive redeploys. Locally falls back to <BASE_DIR>/media which is
# git-ignored.
MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))
# Cap one upload at 25MB by default — adjust if PDFs/photos start
# being larger in practice. Total request budget is the same; ten
# images would mean ten requests, not one heavy one.
AGENT_ATTACHMENT_MAX_BYTES = int(os.getenv("AGENT_ATTACHMENT_MAX_BYTES", str(25 * 1024 * 1024)))

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True

# Shared allowlist: original production/dev origins (do not drop when adding hosts).
_ORIGINAL_TRUSTED_ORIGINS = [
    "https://server-production-e754.up.railway.app",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "https://nordventures.retool.com",
    "https://82f3-8-242-11-50.ngrok-free.app",
]
# Extra origins appended to CORS + CSRF (e.g. Railway staging, prod frontend).
_ADDITIONAL_TRUSTED_ORIGINS = [
    "https://main-server-staging-e5d3.up.railway.app",
    "https://nordventures.up.railway.app",
]
_TRUSTED_ORIGINS = _ORIGINAL_TRUSTED_ORIGINS + _ADDITIONAL_TRUSTED_ORIGINS

# In development, allow all origins for easier testing
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = list(_TRUSTED_ORIGINS)

CSRF_TRUSTED_ORIGINS = list(_TRUSTED_ORIGINS)

# ---------------------------------------------------------------------------
# OpenClaw Agent Configuration
# ---------------------------------------------------------------------------
# The origin(s) where the OpenClaw-built frontend will be hosted.
# Add the actual production URL once known.
OPENCLAW_FRONTEND_ORIGINS = os.getenv(
    "OPENCLAW_FRONTEND_ORIGINS",
    "http://localhost:3000,http://localhost:5173",
).split(",")

# When DEBUG is False, explicitly allow these in CORS:
if not DEBUG:
    CORS_ALLOWED_ORIGINS += [o.strip() for o in OPENCLAW_FRONTEND_ORIGINS if o.strip()]

# Rate limiting for the OpenClaw token (advisory — enforce via reverse proxy
# or django-ratelimit in production).
OPENCLAW_RATE_LIMIT = os.getenv("OPENCLAW_RATE_LIMIT", "600/hour")  # 10 req/min


# ---------------------------------------------------------------------------
# Reconciliation Agent thresholds
# ---------------------------------------------------------------------------
# Read by ``accounting/services/reconciliation_agent_service.py``. Each can be
# overridden per-call (mgmt command flags). Tuned conservatively so v1 only
# auto-accepts the no-regret cohort; raise after observing the false-positive
# rate over a populated set of decisions.
RECONCILIATION_AGENT_AUTO_ACCEPT_THRESHOLD = os.getenv(
    "RECONCILIATION_AGENT_AUTO_ACCEPT_THRESHOLD", "0.95"
)
RECONCILIATION_AGENT_AMBIGUITY_GAP = os.getenv(
    "RECONCILIATION_AGENT_AMBIGUITY_GAP", "0.10"
)
RECONCILIATION_AGENT_MIN_CONFIDENCE = os.getenv(
    "RECONCILIATION_AGENT_MIN_CONFIDENCE", "0.50"
)


# ---------------------------------------------------------------------------
# Internal Sysnord agent (OAuth → OpenAI ChatGPT subscription via Codex API)
# ---------------------------------------------------------------------------
# Replicates OpenClaw / Codex CLI's auth + API flow — see
# ``agent/services/oauth_service.py`` and ``openai_client.py`` for the full
# explanation. Defaults are hardcoded to OpenAI's published Codex constants;
# everything below is overridable via env for testing or if OpenAI ever
# changes the values.
#
# The OAuth dance happens on the operator's laptop (loopback redirect to
# ``http://localhost:1455/auth/callback`` is locked into OpenAI's
# ``client_id``); resulting tokens are POSTed to
# ``/api/agent/connection/import-tokens/`` for storage.

# Encryption at rest for the singleton ``OpenAITokenStore`` (Fernet).
# Generate with::
#
#     python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
AGENT_TOKEN_ENCRYPTION_KEY = os.getenv("AGENT_TOKEN_ENCRYPTION_KEY", "")

# OAuth (auth.openai.com) — empty values fall back to OpenClaw/Codex
# CLI defaults inside ``oauth_service``.
OPENAI_OAUTH_CLIENT_ID = os.getenv("OPENAI_OAUTH_CLIENT_ID", "")
OPENAI_OAUTH_AUTH_URL = os.getenv("OPENAI_OAUTH_AUTH_URL", "")
OPENAI_OAUTH_TOKEN_URL = os.getenv("OPENAI_OAUTH_TOKEN_URL", "")
OPENAI_OAUTH_REDIRECT_URI = os.getenv("OPENAI_OAUTH_REDIRECT_URI", "")
OPENAI_OAUTH_SCOPES = os.getenv("OPENAI_OAUTH_SCOPES", "")
OPENAI_OAUTH_ORIGINATOR = os.getenv("OPENAI_OAUTH_ORIGINATOR", "")
OPENAI_OAUTH_HTTP_TIMEOUT = float(os.getenv("OPENAI_OAUTH_HTTP_TIMEOUT", "15"))

# Experimental: append the Codex Responses API's hosted ``web_search`` tool to
# the agent's tool catalog so the model can answer questions that need fresh
# external info (regulatory updates, market data, news). Default off — the
# Codex backend at ``chatgpt.com/backend-api/codex`` may reject hosted tools
# depending on the originator and the connected ChatGPT plan, and we don't
# want a 400 to block the regular function-tool flow.
AGENT_ENABLE_WEB_SEARCH = os.getenv("AGENT_ENABLE_WEB_SEARCH", "false").lower() in (
    "1", "true", "yes",
)

# Phase 1 — write-tool kill switch. When False (default), every write tool
# refuses to apply mutations even if the agent passes ``dry_run=False``;
# the call still returns the *proposed* changes so the user can preview.
# Flip to True only after operators are comfortable with the audit trail
# in ``AgentWriteAudit`` and the per-tenant policy layer.
AGENT_ALLOW_WRITES = os.getenv("AGENT_ALLOW_WRITES", "false").lower() in (
    "1", "true", "yes",
)

# Default response-body cap for in-process API calls made via
# ``call_internal_api`` and ``call_erp_api`` (bytes).
AGENT_API_RESPONSE_BYTE_CAP = int(os.getenv("AGENT_API_RESPONSE_BYTE_CAP", "30000"))

# Per-conversation token budget. When the cumulative input+output
# exceeds this, new turns are refused with a clear UI message instead
# of silently lopping context. Set to 0 to disable (default 500_000 —
# about 1.5x the 256k context window of gpt-5.4).
AGENT_TOKEN_BUDGET_PER_CONVERSATION = int(os.getenv(
    "AGENT_TOKEN_BUDGET_PER_CONVERSATION", "500000",
))

# Per-tool rate limits — comma-separated ``name:N/window`` rules where
# window is one of s/m/h. Default lets external lookups breathe but
# caps the tightest call sites. Values are advisory and enforced
# in-process via the AgentToolCallLog table.
AGENT_TOOL_RATE_LIMITS = os.getenv(
    "AGENT_TOOL_RATE_LIMITS",
    # Counterparty + central-bank lookups: 60/min. Heavy enough to
    # catch a runaway loop, generous enough for real research.
    "fetch_cnpj_from_receita:60/m,"
    "fetch_bcb_indicator:60/m,"
    "fetch_ptax:60/m,"
    "fetch_cep:60/m,"
    "fetch_bank_by_code:60/m,"
    "fetch_ncm:60/m,"
    "fetch_cnae_info:60/m,"
    "fetch_holidays_brazil:60/m,"
    # ERP calls — Omie has its own quota; cap to 30/min agent-side as
    # belt-and-suspenders.
    "call_erp_api:30/m,"
    # Internal API caller — 120/min keeps a researching agent alive
    # without letting it loop forever.
    "call_internal_api:120/m,"
    # Recon agent runs are heavy (embedding scoring etc.) — 6/min cap.
    "run_reconciliation_agent:6/m"
)

# Comma-separated list of tool names to hide from the agent. Useful in
# staging / per-tenant feature gating. Domain-level disables also work
# via AGENT_DISABLED_DOMAINS (e.g. "erp,external").
AGENT_DISABLED_TOOLS = [
    n.strip() for n in os.getenv("AGENT_DISABLED_TOOLS", "").split(",") if n.strip()
]
AGENT_DISABLED_DOMAINS = [
    n.strip() for n in os.getenv("AGENT_DISABLED_DOMAINS", "").split(",") if n.strip()
]

# Codex Responses API runtime — endpoint, headers, defaults.
OPENAI_CODEX_BASE_URL = os.getenv(
    "OPENAI_CODEX_BASE_URL", "https://chatgpt.com/backend-api/codex",
)
OPENAI_CODEX_RESPONSES_PATH = os.getenv("OPENAI_CODEX_RESPONSES_PATH", "/responses")
# Must be one of OpenAI's whitelisted originator values
# (``codex_cli_rs`` / ``codex_vscode`` / ``codex_sdk_ts`` / ``Codex*``);
# anything else returns 403.
OPENAI_CODEX_ORIGINATOR = os.getenv("OPENAI_CODEX_ORIGINATOR", "codex_cli_rs")
OPENAI_CODEX_BETA = os.getenv("OPENAI_CODEX_BETA", "responses=experimental")
OPENAI_CODEX_USER_AGENT = os.getenv("OPENAI_CODEX_USER_AGENT", "sysnord-agent/1.0")
# Codex Responses model slugs valid as of 2026-05 with a ChatGPT
# subscription: ``gpt-5.5`` (newest, recommended for complex reasoning),
# ``gpt-5.4`` (CLI default), ``gpt-5.4-mini`` (cheapest), ``gpt-5.3-codex``
# (coding specialist). The plain ``gpt-5`` slug is NOT accepted on this
# endpoint.
OPENAI_DEFAULT_MODEL = os.getenv("OPENAI_DEFAULT_MODEL", "gpt-5.5")
OPENAI_REQUEST_TIMEOUT = float(os.getenv("OPENAI_REQUEST_TIMEOUT", "120"))
AGENT_MAX_TOOL_ITERATIONS = int(os.getenv("AGENT_MAX_TOOL_ITERATIONS", "8"))
