# Generated by Django 4.2.7 on 2026-02-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcostingconfig',
            name='auto_ingest_on_nfe_import',
            field=models.BooleanField(default=False, help_text='Automatically create stock movements when NF-e documents are imported.'),
        ),
    ]
