# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0071_add_reconciliation_rule"),
        ("inventory", "0002_add_auto_ingest_on_nfe_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantcostingconfig",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default sales revenue account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="tenantcostingconfig",
            name="purchase_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default purchase / goods receipt account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="tenantcostingconfig",
            name="discount_given_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Default discount given on sales account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
