# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_tenant_config_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingimpact',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cogsallocation',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inventorylayer',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='inventoryvaluationsnapshot',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantcostingconfig',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='accountingimpact',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_a_company_c8346f_idx'),
        ),
        migrations.AddIndex(
            model_name='cogsallocation',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_c_company_959f92_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_i_company_3337cc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_i_company_4eb6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylayer',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_i_company_626679_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryvaluationsnapshot',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_i_company_146415_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_s_company_256e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcostingconfig',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_t_company_28924c_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_u_company_e5921b_idx'),
        ),
        migrations.AddIndex(
            model_name='uomconversion',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_u_company_9687ca_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='inventory_w_company_42c3c8_idx'),
        ),
    ]
