# Generated by Django 4.2.7 on 2026-04-20 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0032_rename_cliente_erp_id_to_erp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement (P&L)'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('general_ledger', 'General Ledger'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.JSONField(help_text='Canonical template document (validated by pydantic on write).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this report type within the tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('template_snapshot', models.JSONField(help_text='Frozen copy of the template document at generation time.')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement (P&L)'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('general_ledger', 'General Ledger'), ('custom', 'Custom Report')], max_length=50)),
                ('periods', models.JSONField(help_text='The ``periods[]`` passed to /calculate/.')),
                ('result', models.JSONField(help_text='The /calculate/ response (lines × periods, memory, warnings).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Soft reference — nulled if the template is deleted. The authoritative structure lives in ``template_snapshot``.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='accounting_reports.reporttemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['company', 'report_type', 'is_active'], name='accounting__company_52448c_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['company', 'is_default'], name='accounting__company_b75b20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporttemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['company', 'report_type', '-generated_at'], name='accounting__company_b6f964_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['company', 'status'], name='accounting__company_68a412_idx'),
        ),
        migrations.AddIndex(
            model_name='reportinstance',
            index=models.Index(fields=['template', '-generated_at'], name='accounting__templat_4047c7_idx'),
        ),
    ]
