# Generated by Django 4.2.7 on 2026-04-21 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0032_rename_cliente_erp_id_to_erp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Which AI endpoint fired — generate_template, refine, chat, explain, etc.', max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost from our per-model pricing table. Not authoritative.', max_digits=12)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('error_type', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, help_text='Tenant the call ran under (soft ref for historical stability).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='multitenancy.company')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the call (null if the user was later deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounting__user_id_ca5e55_idx'), models.Index(fields=['company', '-created_at'], name='accounting__company_fd20e7_idx'), models.Index(fields=['endpoint', '-created_at'], name='accounting__endpoin_9d9b02_idx'), models.Index(fields=['provider', 'model'], name='accounting__provide_0a498c_idx'), models.Index(fields=['status', '-created_at'], name='accounting__status_56a2b8_idx')],
            },
        ),
    ]
