# Generated by Django 4.2.7 on 2024-02-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0003_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
