# Generated by Django 4.2.7 on 2024-12-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_costcenter_allocationbase'),
        ('multitenancy', '0005_alter_company_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='accounts',
            field=models.ManyToManyField(blank=True, default=None, related_name='entities', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='entity',
            name='cost_centers',
            field=models.ManyToManyField(blank=True, default=None, related_name='entities', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='entity',
            name='inherit_accounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='inherit_cost_centers',
            field=models.BooleanField(default=True),
        ),
    ]
