# Generated by Django 4.2.7 on 2024-12-28 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0011_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
    ]
