# Generated by Django 4.2.7 on 2025-01-02 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0012_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.CreateModel(
            name='IntegrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988))),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger_event', models.CharField(choices=[('payroll_approved', 'Payroll Approved'), ('payroll_created', 'Payroll Created')], max_length=50)),
                ('target_module', models.CharField(choices=[('hr', 'Human Resources'), ('accounting', 'Accounting')], max_length=50)),
                ('rule', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
