# Generated by Django 4.2.7 on 2025-01-09 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0014_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationrule',
            name='target_module',
        ),
        migrations.AddField(
            model_name='integrationrule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationrule',
            name='times_executed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='integrationrule',
            name='rule',
            field=models.TextField(help_text='Formula engine code to execute.'),
        ),
        migrations.CreateModel(
            name='IntegrationRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='multitenancy.integrationrule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
