# Generated by Django 4.2.7 on 2025-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0015_remove_integrationrule_target_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationrule',
            name='execution_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationrule',
            name='filter_conditions',
            field=models.TextField(blank=True, help_text='Python expression for filtering payload records. Example: "record[\'department\'] == \'HR\' and record[\'base_salary\'] > 3000"', null=True),
        ),
    ]
