# Generated by Django 4.2.7 on 2025-02-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0017_substitutionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrule',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationrulelog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
            preserve_default=False,
        ),
    ]
