# Generated by Django 4.2.7 on 2025-04-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0018_alter_integrationrule_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('company', 'name')},
        ),
    ]
