# Generated by Django 4.2.7 on 2025-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0019_alter_entity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
