# Generated by Django 4.2.7 on 2025-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0020_customuser_email_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationrule',
            name='use_celery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='column_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='field_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='match_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('regex', 'Regex'), ('caseless', 'Case/Accent Insensitive')], default='exact', help_text="Tipo de comparação:\n- 'exact': igualdade direta.\n- 'regex': usa re.sub.\n- 'caseless': ignora maiúsculas/minúsculas e acentuação.", max_length=50),
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='substitutionrule',
            unique_together={('company', 'model_name', 'field_name', 'column_name', 'column_index', 'match_value')},
        ),
    ]
