# Generated by Django 4.2.7 on 2025-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0021_integrationrule_use_celery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutionrule',
            name='filter_conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
