# Generated by Django 4.2.7 on 2025-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0022_substitutionrule_filter_conditions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substitutionrule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='field_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='substitutionrule',
            name='model_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='substitutionrule',
            unique_together={('company', 'model_name', 'field_name', 'match_value', 'filter_conditions')},
        ),
        migrations.RemoveField(
            model_name='substitutionrule',
            name='column_index',
        ),
        migrations.RemoveField(
            model_name='substitutionrule',
            name='column_name',
        ),
    ]
