# Generated by Django 4.2.7 on 2025-09-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0023_alter_substitutionrule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('row_count', models.IntegerField()),
                ('colnames', models.JSONField()),
                ('row_hash_sample', models.JSONField()),
                ('table_hash', models.CharField(db_index=True, max_length=64)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('jaccard_to_prev', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company_id', 'model_name', '-created_at'], name='multitenanc_company_5d8ee7_idx'), models.Index(fields=['file_sha256'], name='multitenanc_file_sh_e49529_idx'), models.Index(fields=['table_hash'], name='multitenanc_table_h_3de26a_idx')],
            },
        ),
    ]
