# Generated by Django 4.2.7 on 2025-12-04 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0024_importsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTransformationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_sheet_name', models.CharField(help_text='Name of the Excel sheet to process (case-insensitive matching)', max_length=100)),
                ('skip_rows', models.IntegerField(default=0, help_text='Number of rows to skip at the beginning (headers, titles, etc.)')),
                ('header_row', models.IntegerField(default=0, help_text='Row number (0-indexed after skip_rows) containing column headers')),
                ('target_model', models.CharField(help_text='Target model name: Transaction, JournalEntry, BankTransaction, etc.', max_length=100)),
                ('column_mappings', models.JSONField(default=dict, help_text='\n        Map source columns to target fields (case-insensitive matching).\n        Format: {"Source Column Name": "target_field_name"}\n        Example: {"Data Lançamento": "date", "Valor": "amount"}\n        All mapped columns are REQUIRED - import fails if any is missing.\n        ')),
                ('column_concatenations', models.JSONField(blank=True, default=dict, help_text='\n        Combine multiple source columns into one target field.\n        Format: {\n            "target_field": {\n                "columns": ["Col1", "Col2", "Col3"],\n                "separator": " | ",\n                "template": "{Col1} - Doc: {Col2}"\n            }\n        }\n        If template is provided, it overrides separator.\n        ')),
                ('computed_columns', models.JSONField(blank=True, default=dict, help_text='\n        Compute values using Python expressions.\n        Format: {"target_field": "expression"}\n        Available context: row (dict with all columns), Decimal, datetime, re, abs, str, int, float\n        Example: {"amount": "abs(Decimal(str(row[\'Valor\']).replace(\',\', \'.\')))"}\n        ')),
                ('default_values', models.JSONField(blank=True, default=dict, help_text='\n        Default values for fields not in source.\n        Format: {"field_name": value}\n        Example: {"currency_id": 12, "state": "pending"}\n        ')),
                ('row_filter', models.TextField(blank=True, help_text='\n        Python expression to filter rows. Return True to include, False to skip.\n        Available context: row (dict with all columns)\n        Example: "row.get(\'Valor\') and row[\'Valor\'] != 0"\n        ', null=True)),
                ('execution_order', models.IntegerField(default=0, help_text='Order of execution when processing multiple sheets')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['execution_order', 'name'],
                'indexes': [models.Index(fields=['company', 'source_sheet_name'], name='multitenanc_company_1bd61b_idx'), models.Index(fields=['company', 'is_active'], name='multitenanc_company_249f82_idx')],
            },
        ),
        migrations.CreateModel(
            name='ETLPipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transforming', 'Transforming'), ('substituting', 'Substituting'), ('validating', 'Validating'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('is_preview', models.BooleanField(default=False, help_text='True if this was a preview run (no commit)')),
                ('sheets_found', models.JSONField(default=list)),
                ('sheets_processed', models.JSONField(default=list)),
                ('sheets_skipped', models.JSONField(default=list)),
                ('sheets_failed', models.JSONField(default=list)),
                ('total_rows_input', models.IntegerField(default=0)),
                ('total_rows_transformed', models.IntegerField(default=0)),
                ('total_rows_imported', models.IntegerField(default=0)),
                ('records_created', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', '-started_at'], name='multitenanc_company_73d1d0_idx'), models.Index(fields=['company', 'status'], name='multitenanc_company_2022ed_idx'), models.Index(fields=['file_hash'], name='multitenanc_file_ha_78c5ed_idx')],
            },
        ),
    ]
