# Generated by Django 4.2.7 on 2025-12-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0025_importtransformationrule_etlpipelinelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtransformationrule',
            name='extra_fields_for_trigger',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Map Excel columns to extra fields that will be passed to IntegrationRule triggers.\n        These fields are NOT saved to the target model, but included in the trigger payload.\n        \n        Format: {"target_field_name": "Source Column Name"}\n        Example: {"account_path": "Conta", "cost_center_path": "Centro de Custo"}\n        \n        When a Transaction is created, the trigger payload will include:\n        {\n            "transaction_id": 123,\n            "transaction": {...},\n            "extra_fields": {\n                "account_path": "Assets > Banks > Bradesco",\n                "cost_center_path": "Operations"\n            }\n        }\n        '),
        ),
        migrations.AddField(
            model_name='importtransformationrule',
            name='journal_entry_options',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Special options for JournalEntry target model. Enables automatic debit/credit\n        calculation based on amount sign and account direction.\n        \n        Format: {\n            "amount_field": "amount",           # Field containing the amount value\n            "account_lookup_field": "account_path",  # Field containing account identifier\n            "account_lookup_type": "path",      # "path", "code", "id", or "name"\n            "path_separator": " > ",            # Separator for path-based lookup\n            "auto_debit_credit": true           # Auto-calculate debit/credit from amount sign\n        }\n        \n        When auto_debit_credit is true:\n        - Positive amount + debit-normal account (direction=1) → debit_amount\n        - Negative amount + debit-normal account (direction=1) → credit_amount\n        - Positive amount + credit-normal account (direction=-1) → credit_amount\n        - Negative amount + credit-normal account (direction=-1) → debit_amount\n        '),
        ),
        migrations.AddField(
            model_name='importtransformationrule',
            name='trigger_options',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Configure which IntegrationRule triggers to fire after import.\n        \n        Format: {\n            "enabled": true,                    # Enable/disable triggers\n            "events": ["transaction_created"],  # List of events to trigger\n            "use_celery": true                  # Run triggers async via Celery\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='integrationrule',
            name='trigger_event',
            field=models.CharField(choices=[('payroll_approved', 'Payroll Approved'), ('payroll_created', 'Payroll Created'), ('transaction_created', 'Transaction Created (ETL)'), ('journal_entry_created', 'Journal Entry Created (ETL)'), ('etl_import_completed', 'ETL Import Completed')], max_length=50),
        ),
    ]
