# Generated by Django 4.2.7 on 2025-12-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0026_importtransformationrule_extra_fields_for_trigger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importtransformationrule',
            name='journal_entry_options',
        ),
    ]
