# Generated by Django 4.2.7 on 2025-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0027_remove_importtransformationrule_journal_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='etlpipelinelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='importtransformationrule',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='integrationrule',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='integrationrulelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
    ]
