# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='importtransformationrule',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='integrationrule',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='multitenanc_company_b279b4_idx'),
        ),
        migrations.AddIndex(
            model_name='importtransformationrule',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='multitenanc_company_001fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationrule',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='multitenanc_company_725e17_idx'),
        ),
        migrations.AddIndex(
            model_name='substitutionrule',
            index=models.Index(fields=['company', 'cliente_erp_id'], name='multitenanc_company_8259b3_idx'),
        ),
    ]
