# Generated by Django 4.2.7 on 2026-04-23 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0034_add_user_company_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('mode', models.CharField(choices=[('template', 'Template import (v2)'), ('etl', 'ETL pipeline (v2)')], help_text='Which legacy path this session mirrors (template vs ETL).', max_length=16)),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('awaiting_resolve', 'Awaiting resolutions'), ('ready', 'Ready to commit'), ('committing', 'Committing'), ('committed', 'Committed'), ('error', 'Error'), ('discarded', 'Discarded')], db_index=True, default='analyzing', max_length=24)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the uploaded file for dedup/audit.', max_length=64, null=True)),
                ('file_bytes', models.BinaryField(blank=True, help_text='Original uploaded file bytes. Cleared on discard/expiry. Nullable so a deleted-by-TTL session keeps its audit row.', null=True)),
                ('parsed_payload', models.JSONField(blank=True, default=dict, help_text='The output of the analyze front-half: normalised rows per sheet/model, aggregated substitutions applied, parse metadata. Consumed by resolve + commit.')),
                ('open_issues', models.JSONField(blank=True, default=list, help_text='List of unresolved diagnostics. Each item carries {issue_id, type, severity, location, context, proposed_actions}. Resolve mutates this list; an empty list (with no blocking errors) transitions the session to ``ready``.')),
                ('resolutions', models.JSONField(blank=True, default=list, help_text='Accumulated operator decisions. Each item carries {issue_id, action, params, resolved_at}. Audit-only once the session is committed.')),
                ('staged_substitution_rules', models.JSONField(blank=True, default=list, help_text='Rules the operator asked us to create when resolving unmatched references. Materialised into real SubstitutionRule rows in the same DB transaction as commit. Each item is an editable summary the operator can still tweak pre-commit.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Analyze-time config: sheet names, column mappings, auto-JE options for ETL mode, erp_duplicate_behavior, etc. Frozen at analyze; resolve + commit read only.')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Populated on successful commit: counts of records created/updated/deleted per model, rules materialised, warnings. Matches the legacy response shape so frontend code can render it without branching.')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='TTL sweep drops rows past this time; default is 24h from created_at.', null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='multitenanc_company_b279b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='integrationrule',
            name='multitenanc_company_725e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='substitutionrule',
            name='multitenanc_company_8259b3_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanymembership',
            new_name='multitenanc_user_id_b8968b_idx',
            old_name='mt_ucm_user_company_idx',
        ),
        migrations.RenameIndex(
            model_name='usercompanymembership',
            new_name='multitenanc_company_3107f8_idx',
            old_name='mt_ucm_company_role_idx',
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('import_session', 'Import Session (v2 resolve flow)'), ('api', 'API')], db_index=True, default='manual', help_text="Provenance of the rule: 'manual' (operator-created in admin), 'import_session' (staged inside an ImportSession and materialised on commit), 'api' (POSTed programmatically).", max_length=32),
        ),
        migrations.AlterField(
            model_name='importtransformationrule',
            name='erp_duplicate_behavior',
            field=models.CharField(choices=[('update', 'Update existing row when the same ERP key is found'), ('skip', 'Skip row when a row with the same ERP key already exists'), ('error', 'Fail the row when a row with the same ERP key already exists')], default='update', help_text='When an import row resolves to an existing record by ERP key (__erp_id or coalesced erp_id), choose update, skip, or error.', max_length=20),
        ),
        migrations.AlterField(
            model_name='importtransformationrule',
            name='erp_key_coalesce',
            field=models.BooleanField(default=True, help_text='When True, a mapped erp_id on each imported row also drives upsert/delete the same way as a dedicated __erp_id column. Set False to only use __erp_id for ERP-key matching.'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['company', 'erp_id'], name='multitenanc_company_3a1d00_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationrule',
            index=models.Index(fields=['company', 'erp_id'], name='multitenanc_company_561c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='substitutionrule',
            index=models.Index(fields=['company', 'erp_id'], name='multitenanc_company_50b619_idx'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Operator who uploaded the file. Nullable in case the user was deleted after the session was committed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importsession',
            name='transformation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='multitenancy.importtransformationrule'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substitutionrule',
            name='source_session',
            field=models.ForeignKey(blank=True, help_text='The v2 ImportSession whose resolve step produced this rule, if any. Kept for audit; deleting the session does not cascade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialised_rules', to='multitenancy.importsession'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['company', 'status', '-created_at'], name='multitenanc_company_4b31dc_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['company', 'mode', '-created_at'], name='multitenanc_company_daf61e_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['expires_at'], name='multitenanc_expires_6455ed_idx'),
        ),
    ]
