# Generated by Django 4.2.7 on 2026-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0037_importsession_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='cnae_principal',
            field=models.CharField(blank=True, help_text='Código CNAE 7-dígitos da atividade principal.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, help_text='CNPJ normalizado para 14 dígitos sem máscara. Único por tenant quando preenchido (UI valida). Aceita máscara na entrada e a remove no clean().', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_cep',
            field=models.CharField(blank=True, help_text='CEP normalizado para 8 dígitos sem máscara.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='endereco_uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO'), ('EX', 'EX')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial'), ('holding', 'Holding'), ('sociedade', 'Sociedade Simples'), ('fundo', 'Fundo de Investimento'), ('departamento', 'Departamento'), ('centro_de_custo', 'Centro de Custo'), ('projeto', 'Projeto'), ('outro', 'Outro')], default='filial', help_text='Tipo da entidade. CNPJ / IE / IM / regime tributário só fazem sentido para alguns tipos -- a UI condiciona campos obrigatórios por tipo.', max_length=24),
        ),
        migrations.AddField(
            model_name='entity',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='IE (relevante para entidades que recolhem ICMS).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='IM (relevante para entidades que recolhem ISS).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome comercial / marca.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Nome completo no contrato social. ``name`` é o rótulo de display.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI'), ('imune', 'Imune / Isento'), ('nao_aplicavel', 'Não se aplica')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='telefone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='progress',
            field=models.JSONField(blank=True, default=dict, help_text='Phase 6.z-e — live progress snapshot written at stage boundaries outside the commit atomic block. Keys: ``stage`` (parsing / detecting / dry_run / materializing_rules / writing / done), ``sheets_done`` / ``sheets_total``, ``current_sheet``, ``errors_so_far``, ``updated_at``. Empty dict on non-running sessions. Intra-commit row-level progress requires a separate DB connection (future iteration).'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['company', 'cnpj'], name='multitenanc_company_cbf7bd_idx'),
        ),
    ]
