# Generated by Django 4.2.7 on 2026-04-29 19:17

from django.db import migrations, models
import django.db.models.deletion
import multitenancy.models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0038_entity_cnae_principal_entity_cnpj_entity_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnae_principal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, help_text='CNPJ raiz do tenant (matriz). Normalizado para 14 dígitos sem máscara em ``clean()``.', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='BRL', help_text='ISO 4217 (3 letras). Moeda padrão para novos lançamentos / contas.', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='default_locale',
            field=models.CharField(default='pt-BR', help_text='BCP-47 locale tag. Usado em formatação de números/datas.', max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='default_timezone',
            field=models.CharField(default='America/Sao_Paulo', help_text='IANA timezone. Driva agendamentos e cutoffs de relatório.', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_cep',
            field=models.CharField(blank=True, help_text='CEP normalizado para 8 dígitos sem máscara.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco_uf',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO'), ('EX', 'EX')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome comercial / marca exibido em relatórios.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='razao_social',
            field=models.CharField(blank=True, help_text='Nome completo no contrato social.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI'), ('imune', 'Imune / Isento'), ('nao_aplicavel', 'Não se aplica')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telefone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefer_dark_mode',
            field=models.BooleanField(default=False, help_text='Per-user light/dark preference. Tenant ships both modes.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='use_tenant_theme',
            field=models.BooleanField(default=True, help_text="When true, the active tenant's TenantTheme drives brand colours. When false, fall back to the platform default theme. Saved per user, applies globally."),
        ),
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_palette_light', models.JSONField(default=multitenancy.models._default_brand_palette_light)),
                ('brand_palette_dark', models.JSONField(default=multitenancy.models._default_brand_palette_dark)),
                ('category_palette_light', models.JSONField(default=multitenancy.models._default_category_palette_light)),
                ('category_palette_dark', models.JSONField(default=multitenancy.models._default_category_palette_dark)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_dark_url', models.URLField(blank=True, help_text='Optional dark-mode variant of the logo.', max_length=500, null=True)),
                ('favicon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='multitenancy.company')),
            ],
        ),
    ]
