# Generated by Django 4.2.7 on 2026-04-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0039_company_cnae_principal_company_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenanttheme',
            name='favicon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenanttheme',
            name='logo_dark_url',
            field=models.TextField(blank=True, help_text='Optional dark-mode variant of the logo.', null=True),
        ),
        migrations.AlterField(
            model_name='tenanttheme',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
