# Generated by Django 4.2.7 on 2026-04-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0040_alter_tenanttheme_favicon_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prefer_dark_mode_explicit',
            field=models.BooleanField(default=False, help_text='True only after the user clicks the dark/light toggle. While False, the active TenantTheme.default_mode wins -- avoids the migration-default ``prefer_dark_mode=False`` from silently flipping every operator to light mode after deploy.'),
        ),
        migrations.AddField(
            model_name='tenanttheme',
            name='default_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=8),
        ),
    ]
