# Generated by Django 4.2.7 on 2025-11-08 01:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=64)),
                ('num_pages', models.IntegerField(default=0)),
                ('text_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('ocr_data', models.JSONField(default=dict, help_text='Stores per‑page OCR results with engine and profile metadata.')),
                ('doc_type', models.CharField(blank=True, default='', max_length=64)),
                ('doctype_confidence', models.FloatField(default=0.0)),
                ('rules_version', models.CharField(blank=True, default='v0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('tenant_id', models.CharField(default='default', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('label_subtype', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField()),
                ('page', models.IntegerField(default=0)),
                ('char_start', models.IntegerField(default=0)),
                ('char_end', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('anchors_pos', models.JSONField(blank=True, null=True)),
                ('anchors_neg', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='npl.document')),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
            ],
        ),
        migrations.CreateModel(
            name='SpanEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=128)),
                ('dim', models.IntegerField()),
                ('version', models.CharField(default='v0', max_length=32)),
                ('vector', pgvector.django.vector.VectorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='npl.span')),
            ],
        ),
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtype', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('asset_identifier', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('date_ordered', models.DateField(blank=True, null=True)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('date_converted', models.DateField(blank=True, null=True)),
                ('date_cancelled', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.span')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDeadline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deadline_type', models.CharField(max_length=64)),
                ('days', models.IntegerField()),
                ('working_days', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
            ],
        ),
        migrations.CreateModel(
            name='PricingRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.process')),
            ],
        ),
        migrations.CreateModel(
            name='IdpjEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=255)),
                ('masked_identifier', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('result', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
            ],
        ),
        migrations.CreateModel(
            name='Expropriation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, default='', max_length=64)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('auction_round', models.IntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('hammer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.span')),
            ],
        ),
        migrations.CreateModel(
            name='EnforcementAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('result', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('date_ordered', models.DateField(blank=True, null=True)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('converted_to_penhora', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
                ('span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='npl.span')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='npl.process'),
        ),
        migrations.CreateModel(
            name='CourtEventEvidence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evidence_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
                ('span', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.span')),
            ],
        ),
        migrations.AddField(
            model_name='courtevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='npl.eventtype'),
        ),
        migrations.AddField(
            model_name='courtevent',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='npl.process'),
        ),
        migrations.AddField(
            model_name='courtevent',
            name='spans',
            field=models.ManyToManyField(through='npl.CourtEventEvidence', to='npl.span'),
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(blank=True, default='', max_length=64)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('updated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('competence', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_installments', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npl.courtevent')),
            ],
        ),
    ]
