# Generated by Django 4.2.7 on 2025-11-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('anchors_strong', models.TextField(blank=True, help_text="Âncoras fortes separadas por ';' (e.g. 'decido; defiro')")),
                ('anchors_weak', models.TextField(blank=True, help_text="Âncoras fracas separadas por ';'")),
                ('anchors_negative', models.TextField(blank=True, help_text="Âncoras negativas separadas por ';'")),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='no_process_found',
            field=models.BooleanField(default=False, help_text='Verdadeiro se nenhum número de processo foi detectado.'),
        ),
        migrations.AddField(
            model_name='document',
            name='process_number_raw',
            field=models.CharField(blank=True, default='', help_text='Número de processo extraído do texto (formato bruto).', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_data',
            field=models.JSONField(default=dict, help_text='Resultados de OCR por página com metadados.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process',
            field=models.ForeignKey(blank=True, help_text='O processo associado, se conhecido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='npl.process'),
        ),
    ]
