# Generated by Django 4.2.7 on 2025-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0002_doctyperule_document_no_process_found_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('anchors_strong', models.TextField(blank=True, help_text="Âncoras fortes separadas por ';' (e.g. 'converto a penhora; defiro a penhora')")),
                ('anchors_weak', models.TextField(blank=True, help_text="Âncoras fracas separadas por ';'")),
                ('anchors_negative', models.TextField(blank=True, help_text="Âncoras negativas separadas por ';'")),
                ('embedding_model', models.CharField(default='nomic-embed-text', help_text="Modelo de embedding usado nas similaridades (usar 'nomic' por padrão)", max_length=128)),
                ('anchor_embeddings', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
