# Generated by Django 4.2.7 on 2025-11-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0003_spanrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_stats',
            field=models.JSONField(blank=True, help_text='Métricas de desempenho (tempo, contagem de parágrafos, spans etc.)', null=True),
        ),
    ]
