# Generated by Django 4.2.7 on 2025-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0004_document_processing_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_mode',
            field=models.CharField(choices=[('all_paragraphs', 'Todos os parágrafos'), ('spans_only', 'Apenas spans'), ('none', 'Sem embeddings')], default='all_paragraphs', help_text='Define como os embeddings serão gerados para este documento.', max_length=20),
        ),
    ]
