# Generated by Django 4.2.7 on 2025-11-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0005_document_embedding_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='negative_anchor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='span',
            name='strong_anchor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='span',
            name='weak_anchor_count',
            field=models.IntegerField(default=0),
        ),
    ]
