# Generated by Django 4.2.7 on 2025-11-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0006_span_negative_anchor_count_span_strong_anchor_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanrule',
            name='doc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='span_rules', to='npl.doctyperule'),
            preserve_default=False,
        ),
    ]
