# Generated by Django 4.2.7 on 2025-11-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0007_spanrule_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctyperule',
            name='doc_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='spanrule',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
