# Generated by Django 4.2.7 on 2025-11-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0008_alter_doctyperule_doc_type_alter_spanrule_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanrule',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spanrule',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='spanrule',
            unique_together={('doc_type', 'label')},
        ),
    ]
