# Generated by Django 4.2.7 on 2025-11-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0009_alter_spanrule_description_alter_spanrule_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='debug_mode',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, armazena informações detalhadas de debug (âncoras, pesos, scores).'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_anchors',
            field=models.JSONField(blank=True, help_text="Per-rule anchors per strategy: {'rule_literal': [...], 'ai_anchor': [...]}", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_strategy',
            field=models.CharField(choices=[('rule_literal', 'Rule literal / embeddings'), ('ai_anchor', 'AI-assisted anchors')], default='rule_literal', help_text='Strategy that determined doc_type.', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='doctype_debug',
            field=models.JSONField(blank=True, help_text='Para cada DocTypeRule: âncoras encontradas, pesos e score final.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='Nome original do arquivo enviado (para debug e display).', max_length=255),
        ),
        migrations.AddField(
            model_name='span',
            name='span_strategy',
            field=models.CharField(choices=[('rule_literal', 'Rule literal / embeddings'), ('ai_anchor', 'AI-assisted anchors')], default='rule_literal', help_text='Strategy used to create this span.', max_length=32),
        ),
    ]
