# Generated by Django 4.2.7 on 2025-11-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0010_document_debug_mode_document_doc_type_anchors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='store_file',
            field=models.BooleanField(default=False, help_text='If true, persist the uploaded file; otherwise discard after OCR.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_data',
            field=models.JSONField(blank=True, default=dict, help_text='Resultados de OCR por página com metadados.'),
        ),
    ]
