# Generated by Django 4.2.7 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npl', '0011_document_store_file_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctyperule',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='spanrule',
            name='cliente_erp_id',
            field=models.CharField(blank=True, db_index=True, help_text="Stable identifier from the client's ERP (Omie/codigo, etc.) for upsert and sync.", max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='spanrule',
            index=models.Index(fields=['cliente_erp_id'], name='npl_spanrul_cliente_307de2_idx'),
        ),
    ]
