import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { reconApi } from "./api"
import { useTenant } from "@/providers/TenantProvider"

const qk = {
  tasks: (sub: string) => ["recon", sub, "tasks"] as const,
  task: (sub: string, id: number) => ["recon", sub, "tasks", id] as const,
  queued: (sub: string) => ["recon", sub, "tasks", "queued"] as const,
  configs: (sub: string) => ["recon", sub, "configs"] as const,
  pipelines: (sub: string) => ["recon", sub, "pipelines"] as const,
  unreconciled: (sub: string, params: unknown) => ["recon", sub, "unreconciled", params] as const,
  balances: (sub: string, params: unknown) => ["recon", sub, "balances", params] as const,
}

function useSub() {
  const { tenant } = useTenant()
  return tenant?.subdomain ?? ""
}

export function useReconTasks(params?: { status?: string; pollMs?: number }) {
  const sub = useSub()
  return useQuery({
    queryKey: qk.tasks(sub),
    queryFn: () => reconApi.listTasks({ status: params?.status, ordering: "-id" }),
    enabled: !!sub,
    refetchInterval: params?.pollMs,
  })
}

export function useActiveTasks(pollMs = 3000) {
  const sub = useSub()
  return useQuery({
    queryKey: qk.queued(sub),
    queryFn: () => reconApi.queuedTasks(),
    enabled: !!sub,
    refetchInterval: pollMs,
  })
}

export function useReconTask(id: number | null, pollMs?: number) {
  const sub = useSub()
  return useQuery({
    queryKey: id ? qk.task(sub, id) : ["recon", sub, "tasks", "none"],
    queryFn: () => reconApi.getTask(id as number),
    enabled: !!sub && id != null,
    refetchInterval: (q) => {
      const data = q.state.data
      if (!data) return pollMs ?? false
      if (data.status === "running" || data.status === "queued") return pollMs ?? 2000
      return false
    },
  })
}

export function useReconConfigs() {
  const sub = useSub()
  return useQuery({ queryKey: qk.configs(sub), queryFn: reconApi.listConfigs, enabled: !!sub })
}

export function useReconPipelines() {
  const sub = useSub()
  return useQuery({ queryKey: qk.pipelines(sub), queryFn: reconApi.listPipelines, enabled: !!sub })
}

/**
 * Fetch a single config (with description + weights) lazily. Used by the
 * rule drawer to show the selected rule's description without paying the
 * cost of fetching every config up front.
 */
export function useReconConfig(id: number | null) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "config", id],
    queryFn: () => reconApi.getConfig(id as number),
    enabled: !!sub && id != null,
    staleTime: 60 * 1000,
  })
}

export function useReconPipeline(id: number | null) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "pipeline", id],
    queryFn: () => reconApi.getPipeline(id as number),
    enabled: !!sub && id != null,
    staleTime: 60 * 1000,
  })
}

export function useDailyBalances(params: { date_from: string; date_to: string; bank_account_id?: number }) {
  const sub = useSub()
  return useQuery({
    queryKey: qk.balances(sub, params),
    queryFn: () => reconApi.dailyBalances(params),
    enabled: !!sub && !!params.date_from && !!params.date_to,
  })
}

export function useFilterColumns(kind?: "bank_transaction" | "journal_entry") {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "filter-columns", kind ?? "all"],
    queryFn: () => reconApi.filterColumns(kind),
    enabled: !!sub,
    staleTime: 30 * 60 * 1000,
  })
}

export function usePreviewCounts() {
  return useMutation({ mutationFn: reconApi.previewCounts })
}

export function useReconKPIs(params?: { lookback_days?: number; trend_days?: number }) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "kpis", params],
    queryFn: () => reconApi.getKPIs(params),
    enabled: !!sub,
    staleTime: 60 * 1000,
  })
}

/**
 * Load the persisted suggestions generated by a past reconciliation task.
 * Returns the raw M:M match payloads exactly as the engine emitted them
 * (bank_ids + journal_entries_ids + detail arrays + scores). The Sugestões
 * page has a dedicated task-mode renderer that knows how to display this
 * richer shape directly — no regrouping is done.
 */
export function useTaskSuggestions(
  taskId: number | null,
  params?: { min_confidence?: number; limit?: number },
) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "task-suggestions", taskId, params],
    queryFn: () => reconApi.freshSuggestions(taskId as number, params),
    enabled: !!sub && taskId != null,
    staleTime: 30 * 1000,
  })
}

/**
 * Hydrate the id-only fields of every suggestion by fetching the referenced
 * BankTransaction and JournalEntry rows in one batch per type. Useful for
 * the Sugestões page — most engines (the legacy "fast" paths and the M:M
 * aggregator) persist `bank_ids` / `journal_entries_ids` without the richer
 * `bank_transaction_details` / `journal_entry_details` arrays, which left
 * the UI with no descriptions to show.
 *
 * Only fetches rows whose IDs aren't already present in the payload's detail
 * arrays, so suggestions from engines that *do* include details pay no
 * extra roundtrip.
 */
export function useHydratedTaskSuggestions(
  taskId: number | null,
  params?: { min_confidence?: number; limit?: number },
) {
  const sub = useSub()
  const suggestions = useTaskSuggestions(taskId, params)

  const { bankIdsToFetch, journalIdsToFetch } = (() => {
    const payloads = suggestions.data?.suggestions ?? []
    const bankIds = new Set<number>()
    const journalIds = new Set<number>()
    for (const p of payloads) {
      const bdetails = Array.isArray(p.bank_transaction_details) ? p.bank_transaction_details : []
      const btIds = new Set(bdetails.map((d) => d.id))
      for (const id of p.bank_ids ?? []) {
        if (!btIds.has(id)) bankIds.add(id)
      }
      const jdetails = Array.isArray(p.journal_entry_details) ? p.journal_entry_details : []
      const jeIds = new Set(jdetails.map((d) => d.id))
      for (const id of p.journal_entries_ids ?? []) {
        if (!jeIds.has(id)) journalIds.add(id)
      }
    }
    return {
      bankIdsToFetch: Array.from(bankIds).sort((a, b) => a - b),
      journalIdsToFetch: Array.from(journalIds).sort((a, b) => a - b),
    }
  })()

  const bankRows = useQuery({
    queryKey: ["recon", sub, "task-suggestions", taskId, "bank-hydration", bankIdsToFetch],
    queryFn: () =>
      reconApi.listBankTransactions({
        id__in: bankIdsToFetch.join(","),
        limit: bankIdsToFetch.length,
      }),
    enabled: !!sub && bankIdsToFetch.length > 0,
    staleTime: 60 * 1000,
  })

  const journalRows = useQuery({
    queryKey: ["recon", sub, "task-suggestions", taskId, "journal-hydration", journalIdsToFetch],
    queryFn: () =>
      reconApi.listJournalEntries({
        id__in: journalIdsToFetch.join(","),
        limit: journalIdsToFetch.length,
      }),
    enabled: !!sub && journalIdsToFetch.length > 0,
    staleTime: 60 * 1000,
  })

  return {
    suggestions,
    bankRows,
    journalRows,
  }
}

export function useStartReconTask() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.startTask,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: qk.tasks(sub) })
      qc.invalidateQueries({ queryKey: qk.queued(sub) })
    },
  })
}

export function useCancelReconTask() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (args: { id: number; reason?: string }) => reconApi.cancelTask(args.id, args.reason),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: qk.tasks(sub) })
      qc.invalidateQueries({ queryKey: qk.queued(sub) })
    },
  })
}

export function useDeleteReconTask() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteTask,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: qk.tasks(sub) })
      qc.invalidateQueries({ queryKey: qk.queued(sub) })
    },
  })
}

// ---- Workbench / Suggestions / Config CRUD hooks ----

export function useBankTransactions(params?: Parameters<typeof reconApi.listBankTransactions>[0]) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "bank_transactions", params],
    queryFn: () => reconApi.listBankTransactions(params),
    enabled: !!sub,
  })
}

export function useJournalEntries(params?: Parameters<typeof reconApi.listJournalEntries>[0]) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "journal_entries", params],
    queryFn: () => reconApi.listJournalEntries(params),
    enabled: !!sub,
  })
}

export function useUnmatchedJournalEntries(
  params?: Parameters<typeof reconApi.listUnmatchedJournalEntries>[0],
) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "journal_entries_unmatched", params],
    queryFn: () => reconApi.listUnmatchedJournalEntries(params),
    enabled: !!sub,
  })
}

export function useBankAccountsList() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "bank_accounts"],
    queryFn: reconApi.listBankAccounts,
    enabled: !!sub,
    staleTime: 5 * 60 * 1000,
  })
}

export function useEntities() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "entities"],
    queryFn: reconApi.listEntities,
    enabled: !!sub,
    staleTime: 10 * 60 * 1000,
  })
}

export function useAccounts() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "accounts"],
    queryFn: () => reconApi.listAccounts({ is_active: true }),
    enabled: !!sub,
    staleTime: 10 * 60 * 1000,
  })
}

/**
 * Return the journal entries attached to one transaction. Fires only
 * when `txId` is present (use it to power row-expansion on the
 * transactions page so the list fetch stays single).
 */
export function useTransactionJournalEntries(txId: number | null | undefined) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "transaction", txId, "journal_entries"],
    queryFn: () => reconApi.listTransactionJournalEntries(txId as number),
    enabled: !!sub && txId != null,
    staleTime: 30 * 1000,
  })
}

/**
 * Probe whether an account has any journal entries. Used to lock fields
 * that would be destructive to change after activity (e.g. account_direction
 * flipping signs on historical reports). Returns true/false; undefined while
 * loading or if disabled.
 */
export function useAccountHasEntries(accountId: number | null | undefined) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "account", accountId, "has_entries"],
    queryFn: async () => {
      const rows = await reconApi.listJournalEntries({
        // DRF filterset on JournalEntry accepts `account` id filter.
        // Fetch at most 1 row — we only need existence.
        limit: 1,
        page_size: 1,
        // `account` may not be in the typed filter but DRF allows it.
        ...({ account: accountId } as Record<string, unknown>),
      })
      return Array.isArray(rows) ? rows.length > 0 : false
    },
    enabled: !!sub && accountId != null,
    staleTime: 60 * 1000,
  })
}

export function useSuggestMatches() {
  return useMutation({ mutationFn: reconApi.suggestMatches })
}

export function useCreateSuggestions() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.createSuggestions,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "bank_transactions"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries"] })
    },
  })
}

export function useFinalizeMatches() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.finalizeMatches,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "bank_transactions"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries"] })
    },
  })
}

export function useReconConfigsFull() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "configs_full"],
    queryFn: reconApi.listConfigsFull,
    enabled: !!sub,
  })
}

export function useSaveReconConfig() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateConfig>[1] }) => {
      if (args.id) return reconApi.updateConfig(args.id, args.body)
      return reconApi.createConfig(args.body)
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "configs"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "configs_full"] })
    },
  })
}

export function useDeleteReconConfig() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteConfig,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "configs"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "configs_full"] })
    },
  })
}

// ---- Pipelines CRUD ----

export function useReconPipelinesFull() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "pipelines_full"],
    queryFn: reconApi.listPipelinesFull,
    enabled: !!sub,
  })
}

export function useSaveReconPipeline() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updatePipeline>[1] }) => {
      if (args.id) return reconApi.updatePipeline(args.id, args.body)
      return reconApi.createPipeline(args.body)
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "pipelines"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "pipelines_full"] })
    },
  })
}

export function useDeleteReconPipeline() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deletePipeline,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "pipelines"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "pipelines_full"] })
    },
  })
}

// ---- Bank accounts CRUD ----
export function useSaveBankAccount() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateBankAccount>[1] }) => {
      if (args.id) return reconApi.updateBankAccount(args.id, args.body)
      return reconApi.createBankAccount(args.body as Parameters<typeof reconApi.createBankAccount>[0])
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "bank_accounts"] }),
  })
}

export function useDeleteBankAccount() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteBankAccount,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "bank_accounts"] }),
  })
}

export function useBanks() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "banks"],
    queryFn: reconApi.listBanks,
    enabled: !!sub,
    staleTime: 10 * 60 * 1000,
  })
}

export function useCurrencies() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "currencies"],
    queryFn: reconApi.listCurrencies,
    enabled: !!sub,
    staleTime: 10 * 60 * 1000,
  })
}

// ---- Transactions CRUD ----
export function useTransactions(params?: Parameters<typeof reconApi.listTransactions>[0]) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "transactions", params],
    queryFn: () => reconApi.listTransactions(params),
    enabled: !!sub,
  })
}

export function useSaveTransaction() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateTransaction>[1] }) => {
      if (args.id) return reconApi.updateTransaction(args.id, args.body)
      return reconApi.createTransaction(args.body as Parameters<typeof reconApi.createTransaction>[0])
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "transactions"] }),
  })
}

export function useDeleteTransaction() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteTransaction,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "transactions"] }),
  })
}

export function useTransactionAction() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (args: { id: number; action: "post" | "unpost" | "cancel" }) => {
      if (args.action === "post") return reconApi.postTransaction(args.id)
      if (args.action === "unpost") return reconApi.unpostTransaction(args.id)
      return reconApi.cancelTransaction(args.id)
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "transactions"] }),
  })
}

// ---- Journal Entries CRUD ----
export function useSaveJournalEntry() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateJournalEntry>[1] }) => {
      if (args.id) return reconApi.updateJournalEntry(args.id, args.body)
      return reconApi.createJournalEntry(args.body)
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries"] }),
  })
}

export function useDeleteJournalEntry() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteJournalEntry,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries"] }),
  })
}

// ---- Accounts CRUD ----
export function useSaveAccount() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateAccount>[1] & { company?: number } }) => {
      if (args.id) return reconApi.updateAccount(args.id, args.body)
      return reconApi.createAccount(args.body)
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "accounts"] }),
  })
}

export function useDeleteAccount() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteAccount,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "accounts"] }),
  })
}

// ---- Reconciliations (the match records themselves) ----

const reconciliationsKey = (sub: string, params: unknown) =>
  ["recon", sub, "reconciliations", params] as const
const reconciliationSummariesKey = (sub: string, params: unknown) =>
  ["recon", sub, "reconciliation_summaries", params] as const

export function useReconciliations(
  params?: Parameters<typeof reconApi.listReconciliations>[0],
) {
  const sub = useSub()
  return useQuery({
    queryKey: reconciliationsKey(sub, params),
    queryFn: () => reconApi.listReconciliations(params),
    enabled: !!sub,
  })
}

export function useReconciliationSummaries(
  params?: Parameters<typeof reconApi.listReconciliationSummaries>[0],
) {
  const sub = useSub()
  return useQuery({
    queryKey: reconciliationSummariesKey(sub, params),
    queryFn: () => reconApi.listReconciliationSummaries(params),
    enabled: !!sub,
  })
}

/**
 * Unmatch one reconciliation. On success invalidates the recon list plus the
 * bank-tx / JE caches so the Workbench picks up the newly-freed rows.
 */
export function useUnmatchReconciliation() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (args: { id: number; reason?: string; delete?: boolean }) =>
      reconApi.unmatchReconciliation(args.id, { reason: args.reason, delete: args.delete }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliations"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliation_summaries"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "bank_transactions"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "journal_entries_unmatched"] })
    },
  })
}

export function useUpdateReconciliation() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (args: { id: number; body: Parameters<typeof reconApi.updateReconciliation>[1] }) =>
      reconApi.updateReconciliation(args.id, args.body),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliations"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliation_summaries"] })
    },
  })
}

export function useDeleteReconciliation() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteReconciliation,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliations"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "reconciliation_summaries"] })
    },
  })
}

// ---- Entities CRUD ----
export function useSaveEntity() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: async (args: { id?: number; body: Parameters<typeof reconApi.updateEntity>[1] & { company?: number } }) => {
      if (args.id) return reconApi.updateEntity(args.id, args.body)
      return reconApi.createEntity(args.body)
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "entities"] }),
  })
}

export function useDeleteEntity() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.deleteEntity,
    onSuccess: () => qc.invalidateQueries({ queryKey: ["recon", sub, "entities"] }),
  })
}

/* ---------------- Embeddings ---------------- */

/**
 * Health of the embeddings backend (external model + internal cache).
 * Backend is sync, so no polling by default — consumers can force refetch
 * via TanStack's refetch().
 */
export function useEmbeddingsHealth() {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "embeddings", "health"],
    queryFn: reconApi.embeddingsHealth,
    enabled: !!sub,
    staleTime: 30 * 1000,
  })
}

/**
 * Counts of records still missing a description embedding per model. Polls
 * moderately so the page reflects progress while a backfill is running; the
 * UI can tighten the interval when there's an active job.
 */
export function useEmbeddingsMissingCounts(pollMs = 15_000) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "embeddings", "missing"],
    queryFn: reconApi.embeddingsMissingCounts,
    enabled: !!sub,
    refetchInterval: pollMs,
  })
}

/**
 * Kick off a backfill. Returns the Celery task id so the page can start
 * polling `useEmbeddingsTask`. We opportunistically invalidate the
 * missing-counts query so the UI starts converging immediately rather
 * than waiting for the next poll tick.
 */
export function useStartEmbeddingsBackfill() {
  const sub = useSub()
  const qc = useQueryClient()
  return useMutation({
    mutationFn: reconApi.embeddingsBackfill,
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["recon", sub, "embeddings", "missing"] })
      qc.invalidateQueries({ queryKey: ["recon", sub, "embeddings", "jobs"] })
    },
  })
}

/**
 * Poll a single embedding task. Default interval is 2s while the task is
 * still running and stops automatically on terminal states (SUCCESS,
 * FAILURE, REVOKED). Mirrors the pattern used by `useReconTask`.
 */
export function useEmbeddingsTask(taskId: string | null, pollMs = 2_000) {
  const sub = useSub()
  return useQuery({
    queryKey: taskId ? ["recon", sub, "embeddings", "task", taskId] : ["recon", sub, "embeddings", "task", "none"],
    queryFn: () => reconApi.embeddingsTask(taskId as string),
    enabled: !!sub && !!taskId,
    refetchInterval: (q) => {
      const s = q.state.data?.state?.toUpperCase?.()
      if (!s) return pollMs
      if (s === "SUCCESS" || s === "FAILURE" || s === "REVOKED") return false
      return pollMs
    },
  })
}

/**
 * List recent embedding jobs (active + historical). Defaults mirror what
 * the backend suggests (25 rows, all kinds, include_active=1) so the page
 * shows a unified history+live view.
 */
export function useEmbeddingsJobs(
  params?: { limit?: number; status?: string; kind?: string; include_active?: 0 | 1 },
  pollMs?: number,
) {
  const sub = useSub()
  return useQuery({
    queryKey: ["recon", sub, "embeddings", "jobs", params ?? {}],
    queryFn: () =>
      reconApi.embeddingsJobs({
        limit: params?.limit ?? 25,
        status: params?.status ?? "any",
        kind: params?.kind ?? "embeddings",
        include_active: params?.include_active ?? 1,
      }),
    enabled: !!sub,
    refetchInterval: pollMs,
  })
}
