# Generated by Django 4.2.7 on 2024-02-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0002_entity_level_entity_lft_entity_rght_entity_tree_id_and_more'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'account_code')},
        ),
    ]
