# Generated by Django 4.2.7 on 2024-12-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0005_alter_company_subdomain'),
        ('accounting', '0003_reconciliation_reconciled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center_type', models.CharField(choices=[('cost', 'Cost'), ('profit', 'Profit')], max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costcenters', to='multitenancy.company')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('month', models.DateField()),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.costcenter')),
                ('profit_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_as_profit', to='accounting.costcenter')),
            ],
            options={
                'unique_together': {('cost_center', 'profit_center', 'month')},
            },
        ),
    ]
