# Generated by Django 4.2.7 on 2024-12-28 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_account_created_by_account_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 11, 59, 40, 418325)),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 11, 59, 40, 418325)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 11, 59, 40, 418325)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 11, 59, 40, 418325)),
        ),
    ]
