# Generated by Django 4.2.7 on 2024-12-28 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0011_alter_company_created_at_alter_company_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0007_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliation',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='bank_transactions',
            field=models.ManyToManyField(related_name='reconciliations', to='accounting.banktransaction'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='journal_entries',
            field=models.ManyToManyField(related_name='reconciliations', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 9, 50, 891847)),
        ),
    ]
