# Generated by Django 4.2.7 on 2024-12-28 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_reconciliation_bank_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='allocationbase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='allocationbase',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 17, 26, 44, 470638)),
        ),
    ]
