# Generated by Django 4.2.7 on 2025-01-02 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='allocationbase',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='allocationbase',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 15, 23, 38, 625988)),
        ),
    ]
