# Generated by Django 4.2.7 on 2025-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder_address',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder_city',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder_country',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder_state',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_holder_zip',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
