# Generated by Django 4.2.7 on 2025-02-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_bankaccount_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
