# Generated by Django 4.2.7 on 2025-02-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_banktransaction_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
