# Generated by Django 4.2.7 on 2025-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_bankaccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch_phone',
        ),
    ]
