# Generated by Django 4.2.7 on 2025-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_remove_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
