# Generated by Django 4.2.7 on 2025-02-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_bankaccount_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_class',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_memo',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_method',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_name',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_reference',
        ),
    ]
