# Generated by Django 4.2.7 on 2025-02-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_account_company_alter_allocationbase_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliation',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='reconciled_on',
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('review', 'Pending Review'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
    ]
