# Generated by Django 4.2.7 on 2025-02-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_reconciliation_reconciled_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['date'], name='accounting__date_60a468_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account'], name='accounting__bank_ac_27449e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['entity'], name='accounting__entity__fddfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='accounting__amount_dd385d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status'], name='accounting__status_f25954_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['transaction'], name='accounting__transac_3c67dd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entity'], name='accounting__entity__374ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['account'], name='accounting__account_62a1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['cost_center'], name='accounting__cost_ce_7e6d81_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='accounting__date_98b3df_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['state'], name='accounting__state_462958_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['amount'], name='accounting__amount_81dbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company'], name='accounting__company_59848c_idx'),
        ),
    ]
