# Generated by Django 4.2.7 on 2025-04-03 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_banktransaction_accounting__date_60a468_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
