# Generated by Django 4.2.7 on 2025-04-04 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_account_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costcenter',
            name='balance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
