# Generated by Django 4.2.7 on 2025-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_costcenter_balance_costcenter_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='balance_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_validated',
            field=models.BooleanField(default=False),
        ),
    ]
