# Generated by Django 4.2.7 on 2025-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0019_alter_entity_unique_together'),
        ('accounting', '0025_banktransaction_balance_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'account_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank', 'account_number', 'branch_id')},
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'name')},
        ),
    ]
