# Generated by Django 4.2.7 on 2025-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_account_level_account_lft_account_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
