# Generated by Django 4.2.7 on 2025-07-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0019_alter_entity_unique_together'),
        ('accounting', '0030_journalentry_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__entity__374ffe_idx',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='entity',
        ),
        migrations.AddField(
            model_name='transaction',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='multitenancy.entity'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['entity'], name='accounting__entity__aeedc0_idx'),
        ),
    ]
