# Generated by Django 4.2.7 on 2025-08-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_remove_account_type_account_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='examples',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='key_words',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
