# Generated by Django 4.2.7 on 2025-08-29 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0019_alter_entity_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0034_reconciliationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationtask',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='ReconciliationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('user', 'User')], default='company', help_text='Who this config applies to: global, company, or user', max_length=20)),
                ('name', models.CharField(help_text="Name of this config, e.g. 'High Precision Match' or 'Loose Match'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('bank_filters', models.JSONField(blank=True, default=dict)),
                ('book_filters', models.JSONField(blank=True, default=dict)),
                ('strategy', models.CharField(choices=[('exact 1-to-1', 'Exact 1-to-1'), ('fuzzy', 'Fuzzy'), ('many-to-many', 'Many-to-Many'), ('optimized', 'Optimized')], default='optimized', max_length=50)),
                ('max_group_size', models.PositiveIntegerField(default=2)),
                ('amount_tolerance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_tolerance_days', models.PositiveIntegerField(default=2)),
                ('min_confidence', models.DecimalField(decimal_places=2, default=0.9, max_digits=4)),
                ('max_suggestions', models.PositiveIntegerField(default=5)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_configs', to='multitenancy.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
