# Generated by Django 4.2.7 on 2025-08-29 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0019_alter_entity_unique_together'),
        ('accounting', '0035_alter_reconciliationtask_status_reconciliationconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reconciliationconfig',
            unique_together={('company', 'user', 'name')},
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('user', 'User'), ('company_user', 'Company + User')], default='company', help_text='Who this config applies to: global, company, user, or company+user', max_length=20),
        ),
    ]
