# Generated by Django 4.2.7 on 2025-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_reconciliationconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='routing_number',
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
