# Generated by Django 4.2.7 on 2025-09-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_remove_banktransaction_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='transaction_type',
        ),
    ]
