# Generated by Django 4.2.7 on 2025-09-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_banktransaction_check_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='bank_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='book_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
