# Generated by Django 4.2.7 on 2025-09-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_alter_reconciliationconfig_bank_filters_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='accounting__entity__fddfbd_idx',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='entity',
        ),
    ]
