# Generated by Django 4.2.7 on 2025-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_remove_banktransaction_accounting__entity__fddfbd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bank_designation_pending',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this line is the cash/bank leg and still awaits assignment to a specific bank GL.'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['bank_designation_pending'], name='accounting__bank_de_c68b34_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(check=models.Q(('bank_designation_pending', True), ('account__isnull', False), _connector='OR'), name='je_pending_or_account_present'),
        ),
    ]
