# Generated by Django 4.2.7 on 2025-09-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_journalentry_bank_designation_pending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
    ]
