# Generated by Django 4.2.7 on 2025-10-02 16:19

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_alter_journalentry_account'),
    ]

    operations = [
        VectorExtension()
    ]
