# Generated by Django 4.2.7 on 2025-10-02 20:22

from django.db import migrations
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_pgvector_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings (embeddinggemma:300m) of the account content', null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings (embeddinggemma:300m) of the bank transaction content', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embeddings (embeddinggemma:300m) of the description content', null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['account_description_embedding'], m=16, name='acct_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['description_embedding'], m=16, name='bank_desc_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['description_embedding'], m=16, name='tx_desc_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
