# Generated by Django 4.2.7 on 2025-11-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0024_importsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0044_account_account_description_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('user', 'User'), ('company_user', 'Company + User')], default='company', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('auto_apply_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Confidence threshold above which matches are auto‑applied.', max_digits=4)),
                ('max_suggestions', models.PositiveIntegerField(default=1000, help_text='Maximum number of suggestions returned in one run.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_pipelines', to='multitenancy.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('company', 'user', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='reconciliationconfig',
            name='max_group_size',
        ),
        migrations.RemoveField(
            model_name='reconciliationconfig',
            name='strategy',
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='amount_weight',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='Weight of amount match in confidence calculation', max_digits=4),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='currency_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Weight of currency match in confidence calculation', max_digits=4),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='date_weight',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Weight of date proximity in confidence calculation', max_digits=4),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='duplicate_window_days',
            field=models.PositiveIntegerField(default=3, help_text='Number of days within which identical transactions are considered duplicates.'),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='embedding_weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Weight of embedding similarity in confidence calculation', max_digits=4),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='fee_accounts',
            field=models.JSONField(blank=True, default=list, help_text='List of account codes representing fees to include in group sums.', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='max_group_size_bank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='max_group_size_book',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='text_similarity',
            field=models.JSONField(blank=True, default=dict, help_text='Settings for text and embedding similarity (e.g. use_trgm, use_embedding, weights).', null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='max_suggestions',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ReconciliationPipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('max_group_size_bank', models.PositiveIntegerField(blank=True, null=True)),
                ('max_group_size_book', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_tolerance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_tolerance_days', models.PositiveIntegerField(blank=True, null=True)),
                ('text_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='accounting.reconciliationconfig')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='accounting.reconciliationpipeline')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pipeline', 'order')},
            },
        ),
    ]
