# Generated by Django 4.2.7 on 2025-11-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_journalentry_is_cash_journalentry_is_reconciled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
