# Generated by Django 4.2.7 on 2025-11-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_journalentry_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconciliationpipelinestage',
            old_name='date_tolerance_days',
            new_name='avg_date_delta_days',
        ),
        migrations.RenameField(
            model_name='reconciliationpipelinestage',
            old_name='text_weight',
            new_name='embedding_weight',
        ),
        migrations.RemoveField(
            model_name='reconciliationconfig',
            name='date_tolerance_days',
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='avg_date_delta_days',
            field=models.PositiveIntegerField(default=2, help_text='Max |Δ| between group weighted-average dates.'),
        ),
        migrations.AddField(
            model_name='reconciliationconfig',
            name='group_span_days',
            field=models.PositiveIntegerField(default=2, help_text='Max span inside a candidate group.'),
        ),
        migrations.AddField(
            model_name='reconciliationpipelinestage',
            name='amount_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationpipelinestage',
            name='currency_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationpipelinestage',
            name='date_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationpipelinestage',
            name='group_span_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='amount_weight',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='currency_weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='date_weight',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='duplicate_window_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='embedding_weight',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='fee_accounts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('company', 'Company'), ('user', 'User'), ('company_user', 'Company + User')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationconfig',
            name='text_similarity',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
