# Generated by Django 4.2.7 on 2025-11-18 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_rename_date_tolerance_days_reconciliationpipelinestage_avg_date_delta_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='soft_time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Soft runtime limit in seconds for this config's reconciliation run.", null=True),
        ),
        migrations.AddField(
            model_name='reconciliationpipeline',
            name='soft_time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Soft runtime limit in seconds for runs using this pipeline.', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='auto_match_applied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='auto_match_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='auto_match_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='bank_candidates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounting.reconciliationconfig'),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='config_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='journal_candidates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='matched_bank_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='matched_journal_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounting.reconciliationpipeline'),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='pipeline_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='soft_time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Soft runtime limit in seconds used for this reconciliation run (from config or pipeline).', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationtask',
            name='suggestion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reconciliationpipeline',
            name='auto_apply_score',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Confidence threshold above which matches are auto-applied.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='reconciliationtask',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reconciliationtask',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reconciliationtask',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='reconciliationtask',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationtask',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
