# Generated by Django 4.2.7 on 2025-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_reconciliationconfig_soft_time_limit_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='allow_mixed_signs',
            field=models.BooleanField(default=False, help_text='If false, only match groups where all amounts have the same sign as the bank. If true, allow groups that mix positive and negative amounts.'),
        ),
    ]
