# Generated by Django 4.2.7 on 2025-11-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_reconciliationconfig_allow_mixed_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationconfig',
            name='max_alternatives_per_match',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
