# Generated by Django 4.2.7 on 2025-11-24 16:46

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0051_reconciliationconfig_max_alternatives_per_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('match_type', models.CharField(db_index=True, max_length=32)),
                ('confidence_score', models.DecimalField(db_index=True, decimal_places=4, max_digits=5)),
                ('abs_amount_diff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bank_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('journal_entry_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=16)),
                ('decision_source', models.CharField(blank=True, choices=[('auto_100', 'Auto match 100%'), ('user', 'User action'), ('system', 'System')], db_index=True, max_length=16, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_suggestion_decisions', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='accounting.reconciliation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounting.reconciliationtask')),
            ],
            options={
                'indexes': [models.Index(fields=['task', '-confidence_score'], name='accounting__task_id_585a7e_idx'), models.Index(fields=['task', 'match_type'], name='accounting__task_id_820a3c_idx'), models.Index(fields=['company_id', 'match_type'], name='accounting__company_f12e0b_idx'), models.Index(fields=['task', 'status'], name='accounting__task_id_b53a79_idx')],
            },
        ),
    ]
