# Generated by Django 4.2.7 on 2025-11-29 19:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0024_importsnapshot'),
        ('accounting', '0052_reconciliationsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('report_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('as_of_date', models.DateField(blank=True, help_text='For balance sheet: the specific date. For P&L: same as end_date.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.currency')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Balance Sheet')", max_length=200)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement (P&L)'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('general_ledger', 'General Ledger'), ('custom', 'Custom Report')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this report type')),
                ('show_zero_balances', models.BooleanField(default=False)),
                ('show_account_codes', models.BooleanField(default=True)),
                ('show_percentages', models.BooleanField(default=False)),
                ('group_by_cost_center', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementLineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(help_text='Order of this line in the statement')),
                ('label', models.CharField(help_text='Line item label', max_length=200)),
                ('line_type', models.CharField(choices=[('header', 'Header/Section'), ('account', 'Account'), ('subtotal', 'Subtotal'), ('total', 'Total'), ('spacer', 'Spacer')], default='account', max_length=20)),
                ('account_code_prefix', models.CharField(blank=True, help_text='Match accounts with code starting with this prefix', max_length=50, null=True)),
                ('account_path_contains', models.CharField(blank=True, help_text='Match accounts with path containing this string', max_length=200, null=True)),
                ('account_ids', models.JSONField(blank=True, default=list, help_text='List of account IDs to include in this line')),
                ('calculation_type', models.CharField(choices=[('sum', 'Sum'), ('difference', 'Difference (Debit - Credit)'), ('balance', 'Balance (with account_direction)'), ('formula', 'Formula')], default='balance', help_text='How to calculate the line value', max_length=20)),
                ('formula', models.CharField(blank=True, help_text="Formula referencing other line numbers (e.g., 'L1 + L2 - L3')", max_length=500, null=True)),
                ('indent_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_bold', models.BooleanField(default=False)),
                ('show_negative_in_parentheses', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, help_text='Specific account for this line', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account')),
                ('parent_line', models.ForeignKey(blank=True, help_text='Parent line for hierarchical grouping', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lines', to='accounting.financialstatementlinetemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_templates', to='accounting.financialstatementtemplate')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('line_type', models.CharField(max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated balance for this line', max_digits=18)),
                ('indent_level', models.IntegerField(default=0)),
                ('is_bold', models.BooleanField(default=False)),
                ('account_ids', models.JSONField(blank=True, default=list, help_text='Account IDs that contributed to this line')),
                ('line_template', models.ForeignKey(blank=True, help_text='Reference to template line (may be null if template changed)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.financialstatementlinetemplate')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.financialstatement')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('comparison_type', models.CharField(choices=[('period_over_period', 'Period over Period'), ('year_over_year', 'Year over Year'), ('budget_vs_actual', 'Budget vs Actual'), ('custom', 'Custom')], default='period_over_period', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_base', to='accounting.financialstatement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('comparison_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_comparison', to='accounting.financialstatement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounting.financialstatementtemplate'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='financialstatementtemplate',
            index=models.Index(fields=['company', 'report_type', 'is_active'], name='accounting__company_e75ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatementtemplate',
            index=models.Index(fields=['company', 'is_default'], name='accounting__company_9ad09f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatementtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='financialstatementlinetemplate',
            unique_together={('template', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='financialstatementline',
            index=models.Index(fields=['statement', 'line_number'], name='accounting__stateme_f94b32_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatementcomparison',
            index=models.Index(fields=['company', 'base_statement'], name='accounting__company_2dbc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['company', 'report_type', 'end_date'], name='accounting__company_d50573_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['company', 'status'], name='accounting__company_0e53fd_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['template', 'end_date'], name='accounting__templat_1753b2_idx'),
        ),
    ]
