# Generated by Django 4.2.7 on 2025-11-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_financialstatement_financialstatementtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='report_type',
            field=models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement (P&L)'), ('cash_flow', 'Cash Flow Statement'), ('trial_balance', 'Trial Balance'), ('general_ledger', 'General Ledger'), ('custom', 'Custom Report')], max_length=50),
        ),
    ]
