# Generated by Django 4.2.7 on 2025-12-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0024_importsnapshot'),
        ('accounting', '0054_alter_financialstatement_report_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'account_code', 'parent', 'name')},
        ),
    ]
