# Generated by Django 4.2.7 on 2025-12-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='allocationbase',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='financialstatementcomparison',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='financialstatementtemplate',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
    ]
