# Generated by Django 4.2.7 on 2026-01-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_account_notes_allocationbase_notes_bank_notes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['status'], name='accounting__status_6c6d41_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['company', 'status'], name='accounting__company_5d8969_idx'),
        ),
    ]
