# Generated by Django 4.2.7 on 2026-01-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_populate_calculation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementlinetemplate',
            name='calculation_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('difference', 'Difference (Debit - Credit)'), ('balance', 'Balance (with account_direction)'), ('formula', 'Formula')], default='balance', help_text='DEPRECATED: Use calculation_method instead', max_length=20),
        ),
    ]
