# Generated by Django 4.2.7 on 2026-01-16 01:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0061_add_reconciliation_m2m_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('year', models.IntegerField(help_text='Year (e.g., 2024)')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('posted_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance for posted transactions only', max_digits=18)),
                ('bank_reconciled_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance for bank-reconciled transactions only', max_digits=18)),
                ('all_opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance for all transactions', max_digits=18)),
                ('posted_ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ending balance for posted transactions only', max_digits=18)),
                ('bank_reconciled_ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ending balance for bank-reconciled transactions only', max_digits=18)),
                ('all_ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ending balance for all transactions', max_digits=18)),
                ('posted_total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debits for posted transactions during the month', max_digits=18)),
                ('posted_total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits for posted transactions during the month', max_digits=18)),
                ('bank_reconciled_total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debits for bank-reconciled transactions during the month', max_digits=18)),
                ('bank_reconciled_total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits for bank-reconciled transactions during the month', max_digits=18)),
                ('all_total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debits for all transactions during the month', max_digits=18)),
                ('all_total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits for all transactions during the month', max_digits=18)),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this balance was last calculated')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this balance has been manually validated')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When this balance was validated', null=True)),
                ('account', models.ForeignKey(help_text='The account this balance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='accounting.account')),
                ('calculated_by', models.ForeignKey(blank=True, help_text='User who triggered the calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency of the balance', on_delete=django.db.models.deletion.CASCADE, to='accounting.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='User who validated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_balance_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'month', 'account'],
                'indexes': [models.Index(fields=['company', 'account', 'year', 'month'], name='accounting__company_7304ab_idx'), models.Index(fields=['company', 'year', 'month'], name='accounting__company_1554ca_idx'), models.Index(fields=['account', 'year', 'month'], name='accounting__account_881348_idx'), models.Index(fields=['calculated_at'], name='accounting__calcula_2a6e17_idx')],
                'unique_together': {('company', 'account', 'year', 'month', 'currency')},
            },
        ),
    ]
