# Generated by Django 4.2.7 on 2026-01-16 00:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        ('accounting', '0061_add_reconciliation_m2m_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True)),
                ('year', models.IntegerField(help_text='Year (e.g., 2024)')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the start of the month', max_digits=18)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance at the end of the month', max_digits=18)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total debits during the month', max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total credits during the month', max_digits=18)),
                ('balance_type', models.CharField(choices=[('posted', 'Posted Transactions Only'), ('bank_reconciled', 'Bank-Reconciled Only'), ('all', 'All Transactions')], help_text="Type of balance: posted (state='posted'), bank_reconciled (is_reconciled=True), or all (everything)", max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='When this balance was last calculated')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this balance has been manually validated')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When this balance was validated', null=True)),
                ('account', models.ForeignKey(help_text='The account this balance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='accounting.account')),
                ('calculated_by', models.ForeignKey(blank=True, help_text='User who triggered the calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(help_text='Currency of the balance', on_delete=django.db.models.deletion.CASCADE, to='accounting.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, help_text='User who validated this balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_balance_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'month', 'account', 'balance_type'],
                'indexes': [models.Index(fields=['company', 'account', 'year', 'month', 'balance_type'], name='accounting__company_7bdf24_idx'), models.Index(fields=['company', 'year', 'month'], name='accounting__company_1554ca_idx'), models.Index(fields=['account', 'year', 'month'], name='accounting__account_881348_idx'), models.Index(fields=['calculated_at'], name='accounting__calcula_2a6e17_idx')],
                'unique_together': {('company', 'account', 'year', 'month', 'currency', 'balance_type')},
            },
        ),
    ]
