# Generated by Django 4.2.7 on 2026-01-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_accountbalancehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountbalancehistory',
            new_name='accounting__company_7304ab_idx',
            old_name='accounting__company_7bdf24_idx',
        ),
    ]
