# Generated by Django 4.2.7 on 2026-01-16 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_accountbalancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='account_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score for account assignment based on historical patterns (0-1, system calculated, read-only)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account_historical_matches',
            field=models.IntegerField(default=0, help_text='Number of historical transactions with same account assignment (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='amount_discrepancy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference between JE amount and bank amount (system calculated, read-only)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='amount_discrepancy_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage difference between JE amount and bank amount (system calculated, read-only)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_date_match',
            field=models.BooleanField(default=False, help_text='Whether dates match within tolerance (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_exact_match',
            field=models.BooleanField(default=False, help_text='Whether amounts match exactly within tolerance (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_perfect_match',
            field=models.BooleanField(default=False, help_text='Both amount and date match within tolerance (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_entry_date_delta',
            field=models.IntegerField(blank=True, help_text='Days between journal entry date and bank date (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='metrics_last_calculated_at',
            field=models.DateTimeField(blank=True, help_text='When metrics were last calculated (system updated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payment_day_delta',
            field=models.IntegerField(blank=True, help_text='Days between transaction date and bank date (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_amount_discrepancy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average discrepancy per journal entry (system calculated, read-only)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_payment_day_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average payment delay across all journal entries (system calculated, read-only)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='days_outstanding',
            field=models.IntegerField(blank=True, help_text='Days from transaction date to first reconciliation (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exact_match_count',
            field=models.IntegerField(default=0, help_text='Number of journal entries with exact amount matches (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='max_payment_day_delta',
            field=models.IntegerField(blank=True, help_text='Maximum payment delay across all journal entries (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metrics_last_calculated_at',
            field=models.DateTimeField(blank=True, help_text='When metrics were last calculated (system updated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='min_payment_day_delta',
            field=models.IntegerField(blank=True, help_text='Minimum payment delay across all journal entries (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='perfect_match_count',
            field=models.IntegerField(default=0, help_text='Number of journal entries with perfect matches (system calculated, read-only)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciliation_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of journal entries that are reconciled (system calculated, read-only)', max_digits=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount_discrepancy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all journal entry discrepancies (system calculated, read-only)', max_digits=12),
        ),
    ]
