# Generated by Django 4.2.7 on 2026-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0063_journalentry_account_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='amount_discrepancy_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage difference between JE amount and bank amount (system calculated, read-only)', max_digits=10, null=True),
        ),
    ]
