# Generated by Django 4.2.7 on 2026-01-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_remove_journalentry_amount_discrepancy_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bank_payment_date_delta',
            field=models.IntegerField(blank=True, help_text='Days between journal entry date (est payment date) and bank transaction date, only for bank-reconciled entries hitting cash accounts (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='avg_bank_payment_date_delta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average bank payment date delta (JE est payment date vs bank date) for journal entries hitting cash accounts (system calculated, read-only)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='max_bank_payment_date_delta',
            field=models.IntegerField(blank=True, help_text='Maximum bank payment date delta for journal entries hitting cash accounts (system calculated, read-only)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='min_bank_payment_date_delta',
            field=models.IntegerField(blank=True, help_text='Minimum bank payment date delta for journal entries hitting cash accounts (system calculated, read-only)', null=True),
        ),
    ]
