# Generated by Django 4.2.7 on 2026-01-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        ('accounting', '0065_journalentry_bank_payment_date_delta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('company', 'name', 'bank', 'account_number', 'branch_id')},
        ),
    ]
