# Generated by Django 4.2.7 on 2026-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_alter_bankaccount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
