# Generated by Django 4.2.7 for performance optimization

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0067_alter_journalentry_description_and_more'),
    ]

    operations = [
        # JournalEntry: account + date for financial statement JE fetches
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['account', 'date'], name='acct_je_account_date_idx'),
        ),
        # JournalEntry: tenant + account + date for report and balance queries
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'account', 'date'], name='acct_je_company_account_date_idx'),
        ),
        # JournalEntry: transaction detail views
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['transaction', 'account'], name='acct_je_transaction_account_idx'),
        ),
        # Transaction: tenant + date range for list views and filters
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'date'], name='acct_tx_company_date_idx'),
        ),
        # BankTransaction: tenant + date range for dashboards and filters
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'date'], name='acct_btx_company_date_idx'),
        ),
        # BankTransaction: tenant + status for status-based filters
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'status'], name='acct_btx_company_status_idx'),
        ),
    ]
