# Generated by Django 4.2.7 on 2026-02-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='accounting__company_f4a3eb_idx',
            old_name='acct_btx_company_date_idx',
        ),
        migrations.RenameIndex(
            model_name='banktransaction',
            new_name='accounting__company_ae204a_idx',
            old_name='acct_btx_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__account_e15fb2_idx',
            old_name='acct_je_account_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__company_d52a8c_idx',
            old_name='acct_je_company_account_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__transac_cc2b60_idx',
            old_name='acct_je_transaction_account_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='accounting__company_67d3f5_idx',
            old_name='acct_tx_company_date_idx',
        ),
    ]
