# Generated by Django 4.2.7 on 2026-02-02 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0028_company_notes_entity_notes_etlpipelinelog_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0070_add_reconciliation_rule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reconciliationrule',
            new_name='accounting__company_61c5c0_idx',
            old_name='accounting__company_rule_t_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationrule',
            new_name='accounting__company_c3918e_idx',
            old_name='accounting__company_status_idx',
        ),
        migrations.AlterField(
            model_name='reconciliationrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_company', to='multitenancy.company'),
        ),
        migrations.AlterField(
            model_name='reconciliationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reconciliationrule',
            name='notes',
            field=models.TextField(blank=True, help_text='Metadata and notes about how this record was created (source, filename, function, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
