# Generated by Django migration — tag fields and reconciliation status choice extension

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0073_transaction_boleto_cnpj_and_recon_require_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Free-text label for grouping lines in reconciliation workflows.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Free-text label for grouping lines in reconciliation workflows.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="reconciliation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("open", "Open (partial)"),
                    ("matched", "Matched"),
                    ("unmatched", "Unmatched"),
                    ("review", "Pending Review"),
                    ("approved", "Approved"),
                ],
                default="pending",
                help_text="Use open/pending/review for in-progress (non-closed) reconciliations; matched/approved close the match.",
                max_length=50,
            ),
        ),
    ]
