# Generated by Django 4.2.7 on 2026-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0074_journalentry_tag_banktransaction_tag_recon_open_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Data de vencimento do título/obrigação financeira.', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nf_number',
            field=models.CharField(blank=True, db_index=True, help_text='Número da Nota Fiscal associada a esta transação.', max_length=60, null=True),
        ),
    ]
