# Generated by Django 4.2.7 on 2026-04-28 15:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_rename_cliente_erp_id_to_erp_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='accounting__company_486950_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='accounting__company_fde7a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='accounting__company_06b06b_idx',
        ),
        migrations.RemoveIndex(
            model_name='costcenter',
            name='accounting__company_d2938f_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__company_c059f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='accounting__company_78085d_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='report_category',
            field=models.CharField(blank=True, choices=[('ativo_circulante', 'Ativo Circulante'), ('ativo_nao_circulante', 'Ativo Não Circulante'), ('passivo_circulante', 'Passivo Circulante'), ('passivo_nao_circulante', 'Passivo Não Circulante'), ('patrimonio_liquido', 'Patrimônio Líquido'), ('receita_bruta', 'Receita Bruta'), ('deducao_receita', 'Deduções da Receita'), ('custo', 'Custo'), ('despesa_operacional', 'Despesa Operacional'), ('receita_financeira', 'Receita Financeira'), ('despesa_financeira', 'Despesa Financeira'), ('outras_receitas', 'Outras Receitas/Despesas'), ('imposto_sobre_lucro', 'Tributos sobre Lucro'), ('memo', 'Memo / Compensação')], db_index=True, help_text='Coarse CPC 26 line-item category. Nullable; descendants inherit via tree walk (nearest tagged ancestor wins).', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cash', 'Caixa'), ('bank_account', 'Conta Bancária'), ('restricted_cash', 'Caixa Restrito'), ('contra_account', 'Conta Retificadora'), ('non_cash', 'Item Não-Caixa'), ('working_capital', 'Capital de Giro'), ('ebitda_addback', 'Adicionado no EBITDA'), ('non_recurring', 'Não-Recorrente'), ('value_added_input', 'Insumo da DVA'), ('fixed_asset', 'Imobilizado Depreciável'), ('intangible_asset', 'Intangível Amortizável'), ('debt', 'Dívida Onerosa'), ('short_term', 'Curto Prazo'), ('long_term', 'Longo Prazo'), ('icms', 'ICMS'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('iss', 'ISS'), ('ipi', 'IPI'), ('inss', 'INSS'), ('fgts', 'FGTS'), ('irrf', 'IRRF a Compensar'), ('foreign_currency', 'Moeda Estrangeira'), ('intercompany', 'Intercompany'), ('elimination', 'Eliminação Consolidação'), ('accrual', 'Provisão (Accrual)'), ('prepaid', 'Antecipado'), ('product_sales', 'Venda de Produtos'), ('service_revenue', 'Receita de Serviços'), ('subscription_revenue', 'Receita Recorrente / Assinatura'), ('export_revenue', 'Receita de Exportação'), ('jcp', 'Juros sobre Capital Próprio'), ('dividends', 'Dividendos'), ('comprehensive_income', 'Outros Resultados Abrangentes'), ('ifrs16_lease', 'Arrendamento IFRS 16'), ('guaranteed', 'Garantia Concedida')], max_length=48), blank=True, default=list, help_text="Cross-cutting markers (cash, debt, contra_account, ebitda_addback, ...). Closed enum; descendants inherit as a UNION with this account's own tags.", size=None),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, help_text='CNPJ da contraparte para conciliação. Aceita os formatos puro (14 dígitos) ou pontuado (XX.XXX.XXX/XXXX-XX); ``clean_fields`` normaliza para 14 dígitos no banco.', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cnpj',
            field=models.CharField(blank=True, db_index=True, help_text='CNPJ da contraparte para conciliação. Aceita os formatos puro (14 dígitos) ou pontuado (XX.XXX.XXX/XXXX-XX); ``clean_fields`` normaliza para 14 dígitos no banco.', max_length=14, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_096f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='acct_tags_gin'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'report_category'], name='acct_company_category_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_bd80dc_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_d36d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_51b842_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_25711e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'erp_id'], name='accounting__company_04381a_idx'),
        ),
    ]
