# Generated by hand: parallels 0078 for the new ``cashflow_category``
# field on Account. Adds a single nullable CharField with the 15 closed-
# enum CPC 03 sub-line values; backfill is data-only and ships in the
# ``tag_evolat_cashflow`` management command.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0078_taxonomy_fields_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashflow_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fco_recebimentos_clientes', 'FCO · Recebimentos de Clientes'),
                    ('fco_pagamentos_fornecedores', 'FCO · Pagamentos a Fornecedores'),
                    ('fco_pagamentos_empregados', 'FCO · Pagamentos a Empregados'),
                    ('fco_impostos_indiretos', 'FCO · Impostos Indiretos'),
                    ('fco_imposto_renda', 'FCO · IR/CSLL Pagos'),
                    ('fco_juros', 'FCO · Juros Pagos/Recebidos'),
                    ('fco_outros', 'FCO · Outros Recebimentos/Pagamentos'),
                    ('fci_imobilizado', 'FCI · Imobilizado'),
                    ('fci_intangivel', 'FCI · Intangível'),
                    ('fci_investimentos_financeiros', 'FCI · Investimentos Financeiros'),
                    ('fci_outros', 'FCI · Outros Investimentos'),
                    ('fcf_emprestimos', 'FCF · Empréstimos e Financiamentos'),
                    ('fcf_capital', 'FCF · Aporte/Redução de Capital'),
                    ('fcf_dividendos_jcp', 'FCF · Dividendos e JCP'),
                    ('fcf_outros', 'FCF · Outros Financiamentos'),
                ],
                db_index=True,
                help_text=(
                    'DFC line classification (CPC 03 / IAS 7 direct method). '
                    'Nullable; descendants inherit via tree walk. Section '
                    '(FCO/FCI/FCF) is derived from the prefix of this value.'
                ),
                max_length=32,
                null=True,
            ),
        ),
    ]
