# Generated by hand: adds covering ``(company, updated_at)`` indexes
# on the three tables consumed by ``report_cache.data_version()``.
#
# The fingerprint probe runs three ``MAX(updated_at) WHERE company=...``
# queries on every cached report read. Without these indexes Postgres
# falls back to a sequential scan filtered by company; with them it's
# a single index seek per probe (~sub-ms total).
#
# All three indexes are non-unique and append-only safe -- they don't
# change query semantics, only planner choices. ``CREATE INDEX
# CONCURRENTLY`` would be the production-safer flavour but Django
# default ``CREATE INDEX`` blocks writes for the duration of the
# build; on Evolat-scale tables (10s of thousands of rows) that's
# sub-second and acceptable. For multi-million-row tables, switch to
# ``AddIndexConcurrently`` in a follow-up migration.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_account_cashflow_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['company', 'updated_at'],
                name='acct_company_updated_at_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(
                fields=['company', 'updated_at'],
                name='tx_company_updated_at_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(
                fields=['company', 'updated_at'],
                name='je_company_updated_at_idx',
            ),
        ),
    ]
