# Generated by Django 4.2.7 on 2025-08-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multitenancy', '0019_alter_entity_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('model_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_blob', models.BinaryField()),
                ('training_fields', models.JSONField(blank=True, null=True)),
                ('prediction_fields', models.JSONField(blank=True, null=True)),
                ('records_per_account', models.PositiveIntegerField(help_text='Number of recent records used per account when training', null=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='multitenancy.company')),
            ],
            options={
                'ordering': ['-trained_at'],
                'unique_together': {('company', 'name', 'version')},
            },
        ),
    ]
