# Generated by Django 4.2.7 on 2025-09-02 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('tenant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=50)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(default='queued', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
