# Generated by Django 4.2.7 on 2025-09-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multitenancy', '0020_customuser_email_last_sent_at_and_more'),
        ('ML', '0002_mltrainingtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mltrainingtask',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='mltrainingtask',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='training_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mltrainingtask',
            name='company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='ml_training_tasks', to='multitenancy.company'),
            preserve_default=False,
        ),
    ]
